In [1]:
import numpy as np
import pandas as pd
import csv
import sys
import os
  
import matplotlib.pyplot as plt

from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
import warnings
import pickle

max_iters = 501
#n_estimators = 10

def logreg(x,y,filename):

   # Model output file name
   file = (os.path.splitext(filename))[0]
   fname = './models/lr_' + file +'/'

   # File for writing precision,recall, f-measure scores for fraud transactions
   f = open('./prf/lr_'+ file + '_prf' +'.txt' ,'w')
   f.write('precision,recall,f-score \n')

   # Stratified sampling based on Y
   X_train, X_test, y_train, y_test = train_test_split(x, y,stratify=y , test_size=0.30, random_state=42)

   # Create 15% validation set and 15% test set split
   X_val, X_test, y_val, y_test = train_test_split(X_test, y_test,stratify=y_test , test_size=0.50, random_state=42)
   
   #Iterations
   it = 1
   
   # Run training algorithm for multiple class weights
   while it < max_iters:
       cw = {}
       cw[0] = 1
       cw[1] = it
       # Train
       print('**************************************')
       print("Iteration number  " , it)
       lr = LogisticRegression(class_weight = cw)
       print('Class weights ', cw)
       lr.fit(X_train,y_train)

       # Save trained model to disk
       name = fname + str(cw[1]) + '.sav'
       pickle.dump(lr, open(name, 'wb'))

       # Predict on validation data
       y_val_pred = lr.predict(X_val)
       print('Performance on validation data - Confusion matrix')
       print(confusion_matrix(y_val,y_val_pred))
   
       precision,recall,fscore,support=score(y_val,y_val_pred,average=None)
       print('Precision, Recall, F-score, Support  on validation data' )
       print("Precision" , precision)
       print("Recall" , recall)
       print("F-score" , fscore)
       print("Support" , support)

       p1 = precision[1]
       r1 = recall[1]
       f1 = fscore[1]

       f.write(str(p1) +','+ str(r1) + ',' + str(f1) + '\n') 
       it += 1

   f.close()

def run():
   filename = 'm3.csv'
   df = pd.read_csv(filename, usecols = [9,10,11,12,13,14] , header = 0)
   
   results = list(map(int, df['Anomaly'])) 
   print('Number of fraudulent transactions ' , sum(results))

   features = ['Airfare', 'Lodging', 'Meals', 'Other_Transportation', 'Other_Expenses']
   targets = ['Anomaly']

   # Separating out the features and target variables
   x = df.loc[:, features].values
   y = df.loc[:, targets].values
    
   scaler = preprocessing.StandardScaler()
   x = scaler.fit_transform(x)    

   y  = [i for j in y for i in j]
   
   #Ignore warnings
   warnings.filterwarnings("ignore", category=FutureWarning)

   print("***********Logistic Regression**********")
   logreg(x,y,filename)
  
run()

Number of fraudulent transactions  4097
***********Logistic Regression**********
**************************************
Iteration number   1
Class weights  {0: 1, 1: 1}
Performance on validation data - Confusion matrix
[[79313     9]
 [  268   346]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99663236 0.97464789]
Recall [0.99988654 0.56351792]
F-score [0.9982568  0.71413829]
Support [79322   614]
**************************************
Iteration number   2
Class weights  {0: 1, 1: 2}
Performance on validation data - Confusion matrix
[[79307    15]
 [  218   396]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99725872 0.96350365]
Recall [0.9998109  0.64495114]
F-score [0.99853318 0.77268293]
Support [79322   614]
**************************************
Iteration number   3
Class weights  {0: 1, 1: 3}
Performance on validation data - Confusion matrix
[[79302    20]
 [  194   420]]
Precision, Recall, F-score, Support  on validation data
Precis

/home/sandisk/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Performance on validation data - Confusion matrix
[[78762   560]
 [  175   439]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99778304 0.43943944]
Recall [0.99294017 0.71498371]
F-score [0.99535571 0.54432734]
Support [79322   614]
**************************************
Iteration number   17
Class weights  {0: 1, 1: 17}


/home/sandisk/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Performance on validation data - Confusion matrix
[[78762   560]
 [  189   425]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99760611 0.43147208]
Recall [0.99294017 0.69218241]
F-score [0.99526767 0.53158224]
Support [79322   614]
**************************************
Iteration number   18
Class weights  {0: 1, 1: 18}
Performance on validation data - Confusion matrix
[[79200   122]
 [   32   582]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99959612 0.82670455]
Recall [0.99846197 0.94788274]
F-score [0.99902872 0.8831563 ]
Support [79322   614]
**************************************
Iteration number   19
Class weights  {0: 1, 1: 19}


/home/sandisk/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Performance on validation data - Confusion matrix
[[78648   674]
 [  180   434]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99771655 0.39169675]
Recall [0.99150299 0.70684039]
F-score [0.99460006 0.50406504]
Support [79322   614]
**************************************
Iteration number   20
Class weights  {0: 1, 1: 20}


/home/sandisk/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Performance on validation data - Confusion matrix
[[78622   700]
 [  171   443]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99782976 0.38757655]
Recall [0.99117521 0.72149837]
F-score [0.99449135 0.50426864]
Support [79322   614]
**************************************
Iteration number   21
Class weights  {0: 1, 1: 21}
Performance on validation data - Confusion matrix
[[79104   218]
 [   14   600]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99982305 0.73349633]
Recall [0.99725171 0.9771987 ]
F-score [0.99853572 0.83798883]
Support [79322   614]
**************************************
Iteration number   22
Class weights  {0: 1, 1: 22}
Performance on validation data - Confusion matrix
[[79029   293]
 [    7   607]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99991143 0.67444444]
Recall [0.9963062  0.98859935]
F-score [0.99810556 0.80184941]
Support [79322   614]
**************************************
Iteration num

Performance on validation data - Confusion matrix
[[77851  1471]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.29448441]
Recall [0.98145533 1.        ]
F-score [0.99064089 0.45498333]
Support [79322   614]
**************************************
Iteration number   45
Class weights  {0: 1, 1: 45}
Performance on validation data - Confusion matrix
[[77832  1490]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.        0.2918251]
Recall [0.9812158 1.       ]
F-score [0.99051885 0.4518028 ]
Support [79322   614]
**************************************
Iteration number   46
Class weights  {0: 1, 1: 46}
Performance on validation data - Confusion matrix
[[77808  1514]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.28853383]
Recall [0.98091324 1.        ]
F-score [0.99036467 0.44784829]
Support [79322   614]
**************************************
Iteration number 

Performance on validation data - Confusion matrix
[[77366  1956]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.23891051]
Recall [0.97534102 1.        ]
F-score [0.98751659 0.38567839]
Support [79322   614]
**************************************
Iteration number   69
Class weights  {0: 1, 1: 69}
Performance on validation data - Confusion matrix
[[77345  1977]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.23697414]
Recall [0.97507627 1.        ]
F-score [0.98738088 0.38315133]
Support [79322   614]
**************************************
Iteration number   70
Class weights  {0: 1, 1: 70}
Performance on validation data - Confusion matrix
[[77330  1992]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.23561013]
Recall [0.97488717 1.        ]
F-score [0.98728392 0.38136646]
Support [79322   614]
**************************************
Iteration num

Performance on validation data - Confusion matrix
[[76999  2323]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.20905686]
Recall [0.9707143 1.       ]
F-score [0.98513955 0.34581808]
Support [79322   614]
**************************************
Iteration number   93
Class weights  {0: 1, 1: 93}
Performance on validation data - Confusion matrix
[[76984  2338]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.20799458]
Recall [0.9705252 1.       ]
F-score [0.98504216 0.34436343]
Support [79322   614]
**************************************
Iteration number   94
Class weights  {0: 1, 1: 94}
Performance on validation data - Confusion matrix
[[76971  2351]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.20708263]
Recall [0.97036131 1.        ]
F-score [0.98495774 0.3431126 ]
Support [79322   614]
**************************************
Iteration number 

Performance on validation data - Confusion matrix
[[76698  2624]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.18962322]
Recall [0.96691964 1.        ]
F-score [0.98318164 0.31879543]
Support [79322   614]
**************************************
Iteration number   117
Class weights  {0: 1, 1: 117}
Performance on validation data - Confusion matrix
[[76680  2642]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.18857494]
Recall [0.96669272 1.        ]
F-score [0.98306432 0.31731266]
Support [79322   614]
**************************************
Iteration number   118
Class weights  {0: 1, 1: 118}
Performance on validation data - Confusion matrix
[[76671  2651]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.18805513]
Recall [0.96657926 1.        ]
F-score [0.98300565 0.31657644]
Support [79322   614]
**************************************
Iteration

Performance on validation data - Confusion matrix
[[76408  2914]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.17403628]
Recall [0.96326366 1.        ]
F-score [0.98128813 0.29647513]
Support [79322   614]
**************************************
Iteration number   141
Class weights  {0: 1, 1: 141}
Performance on validation data - Confusion matrix
[[76401  2921]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.17369165]
Recall [0.96317541 1.        ]
F-score [0.98124233 0.29597493]
Support [79322   614]
**************************************
Iteration number   142
Class weights  {0: 1, 1: 142}
Performance on validation data - Confusion matrix
[[76390  2932]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.17315285]
Recall [0.96303674 1.        ]
F-score [0.98117037 0.29519231]
Support [79322   614]
**************************************
Iteration

Performance on validation data - Confusion matrix
[[76160  3162]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.16260593]
Recall [0.96013716 1.        ]
F-score [0.97966324 0.27972665]
Support [79322   614]
**************************************
Iteration number   165
Class weights  {0: 1, 1: 165}
Performance on validation data - Confusion matrix
[[76145  3177]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.16196254]
Recall [0.95994806 1.        ]
F-score [0.9795648  0.27877412]
Support [79322   614]
**************************************
Iteration number   166
Class weights  {0: 1, 1: 166}
Performance on validation data - Confusion matrix
[[76134  3188]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.16149395]
Recall [0.95980938 1.        ]
F-score [0.97949259 0.27807971]
Support [79322   614]
**************************************
Iteration

Performance on validation data - Confusion matrix
[[75915  3407]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.15269833]
Recall [0.95704849 1.        ]
F-score [0.97805291 0.26494067]
Support [79322   614]
**************************************
Iteration number   189
Class weights  {0: 1, 1: 189}
Performance on validation data - Confusion matrix
[[75907  3415]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.15239514]
Recall [0.95694763 1.        ]
F-score [0.97800024 0.26448417]
Support [79322   614]
**************************************
Iteration number   190
Class weights  {0: 1, 1: 190}
Performance on validation data - Confusion matrix
[[75897  3425]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.15201783]
Recall [0.95682156 1.        ]
F-score [0.9779344  0.26391575]
Support [79322   614]
**************************************
Iteration

Performance on validation data - Confusion matrix
[[75691  3631]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.14464075]
Recall [0.95422455 1.        ]
F-score [0.97657616 0.2527269 ]
Support [79322   614]
**************************************
Iteration number   213
Class weights  {0: 1, 1: 213}
Performance on validation data - Confusion matrix
[[75679  3643]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.14423303]
Recall [0.95407327 1.        ]
F-score [0.97649693 0.25210429]
Support [79322   614]
**************************************
Iteration number   214
Class weights  {0: 1, 1: 214}
Performance on validation data - Confusion matrix
[[75673  3649]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.14403003]
Recall [0.95399763 1.        ]
F-score [0.97645731 0.25179414]
Support [79322   614]
**************************************
Iteration

Performance on validation data - Confusion matrix
[[75474  3848]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.13760645]
Recall [0.95148887 1.        ]
F-score [0.97514148 0.24192277]
Support [79322   614]
**************************************
Iteration number   237
Class weights  {0: 1, 1: 237}
Performance on validation data - Confusion matrix
[[75461  3861]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.        0.1372067]
Recall [0.95132498 1.        ]
F-score [0.9750554  0.24130478]
Support [79322   614]
**************************************
Iteration number   238
Class weights  {0: 1, 1: 238}
Performance on validation data - Confusion matrix
[[75452  3870]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.13693131]
Recall [0.95121152 1.        ]
F-score [0.9749958  0.24087878]
Support [79322   614]
**************************************
Iteration n

Performance on validation data - Confusion matrix
[[75283  4039]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.13195788]
Recall [0.94908096 1.        ]
F-score [0.97387536 0.2331498 ]
Support [79322   614]
**************************************
Iteration number   261
Class weights  {0: 1, 1: 261}
Performance on validation data - Confusion matrix
[[75269  4053]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.13156203]
Recall [0.94890447 1.        ]
F-score [0.97378243 0.23253172]
Support [79322   614]
**************************************
Iteration number   262
Class weights  {0: 1, 1: 262}
Performance on validation data - Confusion matrix
[[75263  4059]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.13139311]
Recall [0.94882882 1.        ]
F-score [0.9737426  0.23226783]
Support [79322   614]
**************************************
Iteration

Performance on validation data - Confusion matrix
[[75067  4255]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.12610392]
Recall [0.94635788 1.        ]
F-score [0.97243975 0.22396498]
Support [79322   614]
**************************************
Iteration number   285
Class weights  {0: 1, 1: 285}
Performance on validation data - Confusion matrix
[[75056  4266]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.12581967]
Recall [0.94621921 1.        ]
F-score [0.97236653 0.22351656]
Support [79322   614]
**************************************
Iteration number   286
Class weights  {0: 1, 1: 286}
Performance on validation data - Confusion matrix
[[75047  4275]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.12558805]
Recall [0.94610575 1.        ]
F-score [0.97230662 0.22315101]
Support [79322   614]
**************************************
Iteration

Performance on validation data - Confusion matrix
[[74862  4460]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.12100907]
Recall [0.94377348 1.        ]
F-score [0.97107352 0.21589311]
Support [79322   614]
**************************************
Iteration number   309
Class weights  {0: 1, 1: 309}
Performance on validation data - Confusion matrix
[[74853  4469]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.12079481]
Recall [0.94366002 1.        ]
F-score [0.97101346 0.21555204]
Support [79322   614]
**************************************
Iteration number   310
Class weights  {0: 1, 1: 310}
Performance on validation data - Confusion matrix
[[74850  4472]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.12072355]
Recall [0.9436222 1.       ]
F-score [0.97099344 0.2154386 ]
Support [79322   614]
**************************************
Iteration n

Performance on validation data - Confusion matrix
[[74685  4637]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.11693011]
Recall [0.94154207 1.        ]
F-score [0.96989098 0.20937766]
Support [79322   614]
**************************************
Iteration number   333
Class weights  {0: 1, 1: 333}
Performance on validation data - Confusion matrix
[[74675  4647]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.11670785]
Recall [0.941416 1.      ]
F-score [0.96982409 0.20902128]
Support [79322   614]
**************************************
Iteration number   334
Class weights  {0: 1, 1: 334}
Performance on validation data - Confusion matrix
[[74661  4661]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.        0.1163981]
Recall [0.9412395 1.       ]
F-score [0.96973042 0.20852437]
Support [79322   614]
**************************************
Iteration number 

Performance on validation data - Confusion matrix
[[74495  4827]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.        0.1128469]
Recall [0.93914677 1.        ]
F-score [0.96861855 0.2028076 ]
Support [79322   614]
**************************************
Iteration number   357
Class weights  {0: 1, 1: 357}
Performance on validation data - Confusion matrix
[[74486  4836]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.11266055]
Recall [0.93903331 1.        ]
F-score [0.9685582 0.2025066]
Support [79322   614]
**************************************
Iteration number   358
Class weights  {0: 1, 1: 358}
Performance on validation data - Confusion matrix
[[74483  4839]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.11259857]
Recall [0.93899549 1.        ]
F-score [0.96853808 0.20240646]
Support [79322   614]
**************************************
Iteration num

Performance on validation data - Confusion matrix
[[74306  5016]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.10905861]
Recall [0.93676408 1.        ]
F-score [0.9673497 0.1966688]
Support [79322   614]
**************************************
Iteration number   381
Class weights  {0: 1, 1: 381}
Performance on validation data - Confusion matrix
[[74300  5022]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.10894251]
Recall [0.93668843 1.        ]
F-score [0.96730937 0.19648   ]
Support [79322   614]
**************************************
Iteration number   382
Class weights  {0: 1, 1: 382}
Performance on validation data - Confusion matrix
[[74296  5026]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.10886525]
Recall [0.93663801 1.        ]
F-score [0.96728248 0.19635433]
Support [79322   614]
**************************************
Iteration n

Performance on validation data - Confusion matrix
[[74149  5173]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.10609988]
Recall [0.9347848 1.       ]
F-score [0.96629331 0.19184502]
Support [79322   614]
**************************************
Iteration number   405
Class weights  {0: 1, 1: 405}
Performance on validation data - Confusion matrix
[[74145  5177]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.10602659]
Recall [0.93473437 1.        ]
F-score [0.96626636 0.19172521]
Support [79322   614]
**************************************
Iteration number   406
Class weights  {0: 1, 1: 406}
Performance on validation data - Confusion matrix
[[74133  5189]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.10580734]
Recall [0.93458309 1.        ]
F-score [0.96618553 0.19136668]
Support [79322   614]
**************************************
Iteration n

Performance on validation data - Confusion matrix
[[73968  5354]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.10288204]
Recall [0.93250296 1.        ]
F-score [0.96507274 0.18656943]
Support [79322   614]
**************************************
Iteration number   429
Class weights  {0: 1, 1: 429}
Performance on validation data - Confusion matrix
[[73958  5364]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.10270994]
Recall [0.93237689 1.        ]
F-score [0.96500522 0.18628641]
Support [79322   614]
**************************************
Iteration number   430
Class weights  {0: 1, 1: 430}
Performance on validation data - Confusion matrix
[[73945  5377]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.10248706]
Recall [0.93221301 1.        ]
F-score [0.96491743 0.18591976]
Support [79322   614]
**************************************
Iteration

Performance on validation data - Confusion matrix
[[73788  5534]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.09986988]
Recall [0.93023373 1.        ]
F-score [0.96385605 0.18160308]
Support [79322   614]
**************************************
Iteration number   453
Class weights  {0: 1, 1: 453}
Performance on validation data - Confusion matrix
[[73781  5541]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.        0.0997563]
Recall [0.93014548 1.        ]
F-score [0.96380868 0.18141528]
Support [79322   614]
**************************************
Iteration number   454
Class weights  {0: 1, 1: 454}
Performance on validation data - Confusion matrix
[[73777  5545]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.09969151]
Recall [0.93009506 1.        ]
F-score [0.96378161 0.18130814]
Support [79322   614]
**************************************
Iteration n

Performance on validation data - Confusion matrix
[[73647  5675]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.09763078]
Recall [0.92845617 1.        ]
F-score [0.96290098 0.17789367]
Support [79322   614]
**************************************
Iteration number   477
Class weights  {0: 1, 1: 477}
Performance on validation data - Confusion matrix
[[73635  5687]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.09744485]
Recall [0.92830488 1.        ]
F-score [0.96281962 0.17758496]
Support [79322   614]
**************************************
Iteration number   478
Class weights  {0: 1, 1: 478}
Performance on validation data - Confusion matrix
[[73629  5693]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.09735215]
Recall [0.92822924 1.        ]
F-score [0.96277893 0.17743101]
Support [79322   614]
**************************************
Iteration

Performance on validation data - Confusion matrix
[[73475  5847]
 [    0   614]]
Precision, Recall, F-score, Support  on validation data
Precision [1.         0.09503173]
Recall [0.92628779 1.        ]
F-score [0.96173354 0.1735689 ]
Support [79322   614]
