In [2]:
import numpy as np
import pandas as pd
import csv
import sys
import os
  
import matplotlib.pyplot as plt

from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
import warnings
import pickle

max_iters = 501
#n_estimators = 10

def logreg(x,y,filename):

   # Model output file name
   file = (os.path.splitext(filename))[0]
   fname = './models/lr_' + file +'/'

   # File for writing precision,recall, f-measure scores for fraud transactions
   f = open('./prf/lr_'+ file + '_prf' +'.txt' ,'w')
   f.write('precision,recall,f-score \n')

   # Stratified sampling based on Y
   X_train, X_test, y_train, y_test = train_test_split(x, y,stratify=y , test_size=0.30, random_state=42)

   # Create 15% validation set and 15% test set split
   X_val, X_test, y_val, y_test = train_test_split(X_test, y_test,stratify=y_test , test_size=0.50, random_state=42)
   
   #Iterations
   it = 1
   
   # Run training algorithm for multiple class weights
   while it < max_iters:
       cw = {}
       cw[0] = 1
       cw[1] = it
       # Train
       print('**************************************')
       print("Iteration number  " , it)
       lr = LogisticRegression(class_weight = cw)
       print('Class weights ', cw)
       lr.fit(X_train,y_train)

       # Save trained model to disk
       name = fname + str(cw[1]) + '.sav'
       pickle.dump(lr, open(name, 'wb'))

       # Predict on validation data
       y_val_pred = lr.predict(X_val)
       print('Performance on validation data - Confusion matrix')
       print(confusion_matrix(y_val,y_val_pred))
   
       precision,recall,fscore,support=score(y_val,y_val_pred,average=None)
       print('Precision, Recall, F-score, Support  on validation data' )
       print("Precision" , precision)
       print("Recall" , recall)
       print("F-score" , fscore)
       print("Support" , support)

       p1 = precision[1]
       r1 = recall[1]
       f1 = fscore[1]

       f.write(str(p1) +','+ str(r1) + ',' + str(f1) + '\n') 
       it += 1

   f.close()

def run():
   filename = 'm2.csv'
   df = pd.read_csv(filename, usecols = [9,10,11,12,13,14] , header = 0)
   
   results = list(map(int, df['Anomaly'])) 
   print('Number of fraudulent transactions ' , sum(results))

   features = ['Airfare', 'Lodging', 'Meals', 'Other_Transportation', 'Other_Expenses']
   targets = ['Anomaly']

   # Separating out the features and target variables
   x = df.loc[:, features].values
   y = df.loc[:, targets].values
    
   scaler = preprocessing.StandardScaler()
   x = scaler.fit_transform(x)    

   y  = [i for j in y for i in j]
   
   #Ignore warnings
   warnings.filterwarnings("ignore", category=FutureWarning)

   print("***********Logistic Regression**********")
   logreg(x,y,filename)
  
run()

Number of fraudulent transactions  4116
***********Logistic Regression**********
**************************************
Iteration number   1
Class weights  {0: 1, 1: 1}
Performance on validation data - Confusion matrix
[[334984     23]
 [   330    288]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99901585 0.92604502]
Recall [0.99993134 0.46601942]
F-score [0.99947339 0.62002153]
Support [335007    618]
**************************************
Iteration number   2
Class weights  {0: 1, 1: 2}
Performance on validation data - Confusion matrix
[[334961     46]
 [   299    319]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99910815 0.8739726 ]
Recall [0.99986269 0.51618123]
F-score [0.99948528 0.64903357]
Support [335007    618]
**************************************
Iteration number   3
Class weights  {0: 1, 1: 3}
Performance on validation data - Confusion matrix
[[334936     71]
 [   277    341]]
Precision, Recall, F-score, Support  on valida

Performance on validation data - Confusion matrix
[[334379    628]
 [   158    460]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99952771 0.42279412]
Recall [0.99812541 0.74433657]
F-score [0.99882607 0.53927315]
Support [335007    618]
**************************************
Iteration number   25
Class weights  {0: 1, 1: 25}
Performance on validation data - Confusion matrix
[[334357    650]
 [   155    463]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99953664 0.41599281]
Recall [0.99805974 0.74919094]
F-score [0.99879764 0.5349509 ]
Support [335007    618]
**************************************
Iteration number   26
Class weights  {0: 1, 1: 26}
Performance on validation data - Confusion matrix
[[334327    680]
 [   152    466]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99954556 0.40663176]
Recall [0.99797019 0.75404531]
F-score [0.99875726 0.52834467]
Support [335007    618]
**********************************

Performance on validation data - Confusion matrix
[[333792   1215]
 [   111    507]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99966757 0.29442509]
Recall [0.99637321 0.82038835]
F-score [0.99801767 0.43333333]
Support [335007    618]
**************************************
Iteration number   49
Class weights  {0: 1, 1: 49}
Performance on validation data - Confusion matrix
[[333767   1240]
 [   109    509]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99967353 0.29102344]
Recall [0.99629858 0.8236246 ]
F-score [0.9979832  0.43008027]
Support [335007    618]
**************************************
Iteration number   50
Class weights  {0: 1, 1: 50}
Performance on validation data - Confusion matrix
[[333743   1264]
 [   107    511]]
Precision, Recall, F-score, Support  on validation data
Precision [0.9996795  0.28788732]
Recall [0.99622694 0.82686084]
F-score [0.99795023 0.42707898]
Support [335007    618]
**********************************

Performance on validation data - Confusion matrix
[[333294   1713]
 [    79    539]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99976303 0.23934281]
Recall [0.99488667 0.87216828]
F-score [0.99731889 0.37560976]
Support [335007    618]
**************************************
Iteration number   73
Class weights  {0: 1, 1: 73}
Performance on validation data - Confusion matrix
[[333264   1743]
 [    79    539]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99976301 0.23619632]
Recall [0.99479712 0.87216828]
F-score [0.99727388 0.37172414]
Support [335007    618]
**************************************
Iteration number   74
Class weights  {0: 1, 1: 74}
Performance on validation data - Confusion matrix
[[333238   1769]
 [    77    541]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99976899 0.23419913]
Recall [0.99471951 0.87540453]
F-score [0.99723786 0.36953552]
Support [335007    618]
**********************************

Performance on validation data - Confusion matrix
[[332785   2222]
 [    53    565]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99984076 0.20272695]
Recall [0.9933673  0.91423948]
F-score [0.99659352 0.3318649 ]
Support [335007    618]
**************************************
Iteration number   97
Class weights  {0: 1, 1: 97}
Performance on validation data - Confusion matrix
[[332773   2234]
 [    53    565]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99984076 0.20185781]
Recall [0.99333148 0.91423948]
F-score [0.99657549 0.33069944]
Support [335007    618]
**************************************
Iteration number   98
Class weights  {0: 1, 1: 98}
Performance on validation data - Confusion matrix
[[332758   2249]
 [    53    565]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99984075 0.20078181]
Recall [0.99328671 0.91423948]
F-score [0.99655295 0.32925408]
Support [335007    618]
**********************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99988867 0.17648846]
Recall [0.99190763 0.94012945]
F-score [0.99588216 0.2971867 ]
Support [335007    618]
**************************************
Iteration number   120
Class weights  {0: 1, 1: 120}
Performance on validation data - Confusion matrix
[[332266   2741]
 [    37    581]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99988866 0.17489464]
Recall [0.99181808 0.94012945]
F-score [0.99583702 0.29492386]
Support [335007    618]
**************************************
Iteration number   121
Class weights  {0: 1, 1: 121}
Performance on validation data - Confusion matrix
[[332243   2764]
 [    36    582]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99989166 0.17393903]
Recall [0.99174943 0.94174757]
F-score [0.9958039  0.29364279]
Support [335007    618]
**************************************
Iteration number   122
Class weights  {0: 1, 1: 122}
Performance on validati

Performance on validation data - Confusion matrix
[[331708   3299]
 [    26    592]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99992162 0.15214598]
Recall [0.99015244 0.9579288 ]
F-score [0.99501306 0.26258594]
Support [335007    618]
**************************************
Iteration number   144
Class weights  {0: 1, 1: 144}
Performance on validation data - Confusion matrix
[[331684   3323]
 [    26    592]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99992162 0.15121328]
Recall [0.9900808 0.9579288]
F-score [0.99497688 0.26119568]
Support [335007    618]
**************************************
Iteration number   145
Class weights  {0: 1, 1: 145}
Performance on validation data - Confusion matrix
[[331658   3349]
 [    26    592]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99992161 0.15021568]
Recall [0.99000319 0.9579288 ]
F-score [0.99493768 0.25970608]
Support [335007    618]
********************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99995772 0.13425206]
Recall [0.98837338 0.97734628]
F-score [0.9941318  0.23607583]
Support [335007    618]
**************************************
Iteration number   167
Class weights  {0: 1, 1: 167}
Performance on validation data - Confusion matrix
[[331091   3916]
 [    14    604]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99995772 0.13362832]
Recall [0.98831069 0.97734628]
F-score [0.99410009 0.23511094]
Support [335007    618]
**************************************
Iteration number   168
Class weights  {0: 1, 1: 168}
Performance on validation data - Confusion matrix
[[331071   3936]
 [    14    604]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99995771 0.13303965]
Recall [0.98825099 0.97734628]
F-score [0.99406989 0.2341993 ]
Support [335007    618]
**************************************
Iteration number   169
Class weights  {0: 1, 1: 169}
Performance on validati

Performance on validation data - Confusion matrix
[[330307   4700]
 [     9    609]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997275 0.11471087]
Recall [0.98597044 0.98543689]
F-score [0.99292223 0.20550025]
Support [335007    618]
**************************************
Iteration number   191
Class weights  {0: 1, 1: 191}
Performance on validation data - Confusion matrix
[[330264   4743]
 [     9    609]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997275 0.11378924]
Recall [0.98584209 0.98543689]
F-score [0.99285714 0.2040201 ]
Support [335007    618]
**************************************
Iteration number   192
Class weights  {0: 1, 1: 192}
Performance on validation data - Confusion matrix
[[330220   4787]
 [     9    609]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997275 0.11286138]
Recall [0.98571075 0.98543689]
F-score [0.99279053 0.20252744]
Support [335007    618]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99997875 0.09875545]
Recall [0.98335557 0.98867314]
F-score [0.9915975  0.17957384]
Support [335007    618]
**************************************
Iteration number   214
Class weights  {0: 1, 1: 214}
Performance on validation data - Confusion matrix
[[329384   5623]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997875 0.09801091]
Recall [0.98321528 0.98867314]
F-score [0.99152616 0.17834209]
Support [335007    618]
**************************************
Iteration number   215
Class weights  {0: 1, 1: 215}
Performance on validation data - Confusion matrix
[[329336   5671]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997875 0.09726202]
Recall [0.983072   0.98867314]
F-score [0.9914533  0.17710145]
Support [335007    618]
**************************************
Iteration number   216
Class weights  {0: 1, 1: 216}
Performance on validati

Performance on validation data - Confusion matrix
[[328535   6472]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997869 0.08626288]
Recall [0.980681   0.98867314]
F-score [0.99023584 0.15868069]
Support [335007    618]
**************************************
Iteration number   238
Class weights  {0: 1, 1: 238}
Performance on validation data - Confusion matrix
[[328499   6508]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997869 0.08582666]
Recall [0.98057354 0.98867314]
F-score [0.99018105 0.15794235]
Support [335007    618]
**************************************
Iteration number   239
Class weights  {0: 1, 1: 239}
Performance on validation data - Confusion matrix
[[328463   6544]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997869 0.08539483]
Recall [0.98046608 0.98867314]
F-score [0.99012626 0.15721086]
Support [335007    618]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99997864 0.07763659]
Recall [0.9783318  0.98867314]
F-score [0.98903679 0.14396795]
Support [335007    618]
**************************************
Iteration number   261
Class weights  {0: 1, 1: 261}
Performance on validation data - Confusion matrix
[[327723   7284]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997864 0.07739075]
Recall [0.97825717 0.98867314]
F-score [0.98899865 0.14354517]
Support [335007    618]
**************************************
Iteration number   262
Class weights  {0: 1, 1: 262}
Performance on validation data - Confusion matrix
[[327685   7322]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997864 0.07702004]
Recall [0.97814374 0.98867314]
F-score [0.98894068 0.14290726]
Support [335007    618]
**************************************
Iteration number   263
Class weights  {0: 1, 1: 263}
Performance on validati

Performance on validation data - Confusion matrix
[[326951   8056]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997859 0.07049729]
Recall [0.97595274 0.98867314]
F-score [0.9878196  0.13161012]
Support [335007    618]
**************************************
Iteration number   285
Class weights  {0: 1, 1: 285}
Performance on validation data - Confusion matrix
[[326925   8082]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997859 0.07028644]
Recall [0.97587513 0.98867314]
F-score [0.98777984 0.13124262]
Support [335007    618]
**************************************
Iteration number   286
Class weights  {0: 1, 1: 286}
Performance on validation data - Confusion matrix
[[326900   8107]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997859 0.07008488]
Recall [0.97580051 0.98867314]
F-score [0.98774161 0.13089117]
Support [335007    618]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99997854 0.06483447]
Recall [0.97369309 0.98867314]
F-score [0.98666078 0.12168891]
Support [335007    618]
**************************************
Iteration number   308
Class weights  {0: 1, 1: 308}
Performance on validation data - Confusion matrix
[[326151   8856]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997854 0.06453998]
Recall [0.97356473 0.98867314]
F-score [0.98659487 0.12117005]
Support [335007    618]
**************************************
Iteration number   309
Class weights  {0: 1, 1: 309}
Performance on validation data - Confusion matrix
[[326117   8890]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997854 0.06430902]
Recall [0.97346324 0.98867314]
F-score [0.98654276 0.12076292]
Support [335007    618]
**************************************
Iteration number   310
Class weights  {0: 1, 1: 310}
Performance on validati

Performance on validation data - Confusion matrix
[[325435   9572]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997849 0.06000196]
Recall [0.97142746 0.98867314]
F-score [0.98549623 0.11313767]
Support [335007    618]
**************************************
Iteration number   332
Class weights  {0: 1, 1: 332}
Performance on validation data - Confusion matrix
[[325401   9606]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997849 0.05980229]
Recall [0.97132597 0.98867314]
F-score [0.985444   0.11278265]
Support [335007    618]
**************************************
Iteration number   333
Class weights  {0: 1, 1: 333}
Performance on validation data - Confusion matrix
[[325366   9641]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997849 0.05959813]
Recall [0.9712215  0.98867314]
F-score [0.98539023 0.1124195 ]
Support [335007    618]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99997844 0.05608592]
Recall [0.96930512 0.98867314]
F-score [0.9844029 0.1061501]
Support [335007    618]
**************************************
Iteration number   355
Class weights  {0: 1, 1: 355}
Performance on validation data - Confusion matrix
[[324691  10316]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997844 0.05591654]
Recall [0.96920661 0.98867314]
F-score [0.9843521  0.10584669]
Support [335007    618]
**************************************
Iteration number   356
Class weights  {0: 1, 1: 356}
Performance on validation data - Confusion matrix
[[324671  10336]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997844 0.05581438]
Recall [0.96914691 0.98867314]
F-score [0.9843213  0.10566364]
Support [335007    618]
**************************************
Iteration number   357
Class weights  {0: 1, 1: 357}
Performance on validation

Performance on validation data - Confusion matrix
[[324051  10956]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.9999784  0.05282269]
Recall [0.96729621 0.98867314]
F-score [0.98336583 0.10028724]
Support [335007    618]
**************************************
Iteration number   379
Class weights  {0: 1, 1: 379}
Performance on validation data - Confusion matrix
[[324020  10987]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.9999784 0.0526815]
Recall [0.96720367 0.98867314]
F-score [0.98331801 0.10003274]
Support [335007    618]
**************************************
Iteration number   380
Class weights  {0: 1, 1: 380}
Performance on validation data - Confusion matrix
[[323996  11011]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.9999784  0.05257271]
Recall [0.96713203 0.98867314]
F-score [0.98328098 0.0998366 ]
Support [335007    618]
********************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99997836 0.05009429]
Recall [0.96541565 0.98867314]
F-score [0.9823931 0.095357 ]
Support [335007    618]
**************************************
Iteration number   402
Class weights  {0: 1, 1: 402}
Performance on validation data - Confusion matrix
[[323390  11617]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997835 0.04996729]
Recall [0.96532311 0.98867314]
F-score [0.98234519 0.09512689]
Support [335007    618]
**************************************
Iteration number   403
Class weights  {0: 1, 1: 403}
Performance on validation data - Confusion matrix
[[323360  11647]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997835 0.049845  ]
Recall [0.96523356 0.98867314]
F-score [0.98229881 0.09490525]
Support [335007    618]
**************************************
Iteration number   404
Class weights  {0: 1, 1: 404}
Performance on validation

Performance on validation data - Confusion matrix
[[322767  12240]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997831 0.04754494]
Recall [0.96346345 0.98867314]
F-score [0.98138134 0.09072685]
Support [335007    618]
**************************************
Iteration number   426
Class weights  {0: 1, 1: 426}
Performance on validation data - Confusion matrix
[[322737  12270]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997831 0.04743421]
Recall [0.9633739  0.98867314]
F-score [0.98133488 0.09052522]
Support [335007    618]
**************************************
Iteration number   427
Class weights  {0: 1, 1: 427}
Performance on validation data - Confusion matrix
[[322708  12299]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997831 0.04732765]
Recall [0.96328733 0.98867314]
F-score [0.98128997 0.09033116]
Support [335007    618]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99997827 0.04521237]
Recall [0.96148439 0.98867314]
F-score [0.9803536  0.08647042]
Support [335007    618]
**************************************
Iteration number   449
Class weights  {0: 1, 1: 449}
Performance on validation data - Confusion matrix
[[322079  12928]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997827 0.04512889]
Recall [0.96140976 0.98867314]
F-score [0.98031481 0.08631772]
Support [335007    618]
**************************************
Iteration number   450
Class weights  {0: 1, 1: 450}
Performance on validation data - Confusion matrix
[[322055  12952]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997827 0.04504903]
Recall [0.96133812 0.98867314]
F-score [0.98027757 0.08617164]
Support [335007    618]
**************************************
Iteration number   451
Class weights  {0: 1, 1: 451}
Performance on validati

Performance on validation data - Confusion matrix
[[321512  13495]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997823 0.0433149 ]
Recall [0.95971726 0.98867314]
F-score [0.97943417 0.08299375]
Support [335007    618]
**************************************
Iteration number   473
Class weights  {0: 1, 1: 473}
Performance on validation data - Confusion matrix
[[321495  13512]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997823 0.04326276]
Recall [0.95966651 0.98867314]
F-score [0.97940775 0.08289804]
Support [335007    618]
**************************************
Iteration number   474
Class weights  {0: 1, 1: 474}
Performance on validation data - Confusion matrix
[[321475  13532]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997823 0.04320158]
Recall [0.95960681 0.98867314]
F-score [0.97937665 0.08278572]
Support [335007    618]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99997819 0.04162692]
Recall [0.95800983 0.98867314]
F-score [0.97854423 0.07989017]
Support [335007    618]
**************************************
Iteration number   496
Class weights  {0: 1, 1: 496}
Performance on validation data - Confusion matrix
[[320911  14096]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997819 0.04154484]
Recall [0.95792327 0.98867314]
F-score [0.97849907 0.07973899]
Support [335007    618]
**************************************
Iteration number   497
Class weights  {0: 1, 1: 497}
Performance on validation data - Confusion matrix
[[320885  14122]
 [     7    611]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99997819 0.04147153]
Recall [0.95784566 0.98867314]
F-score [0.97845857 0.07960393]
Support [335007    618]
**************************************
Iteration number   498
Class weights  {0: 1, 1: 498}
Performance on validati