In [3]:
import numpy as np
import pandas as pd
import csv
import sys
import os

from sys import platform as sys_pf
if sys_pf == 'darwin':
    import matplotlib
    matplotlib.use("TkAgg")
    import matplotlib.pyplot as plt
    
import matplotlib.pyplot as plt

from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
import warnings
import pickle

max_iters = 513
n_estimators = 10

def logreg(x,y,filename):

   # Model output file name
   file = (os.path.splitext(filename))[0]
   fname = './models/lr_' + file +'/'

   # File for writing precision,recall, f-measure scores for fraud transactions
   f = open('./prf/lr_'+ file + '_prf' +'.txt' ,'w')
   f.write('precision,recall,f-score \n')

   # Stratified sampling based on Y
   X_train, X_test, y_train, y_test = train_test_split(x, y,stratify=y , test_size=0.30, random_state=42)

   # Create 15% validation set and 15% test set split
   X_val, X_test, y_val, y_test = train_test_split(X_test, y_test,stratify=y_test , test_size=0.50, random_state=42)
   
   #Iterations
   it = 1
   
   # Run training algorithm for multiple class weights
   while it < max_iters:
       cw = {}
       cw[0] = 1
       cw[1] = it
       # Train
       print('**************************************')
       print("Iteration number  " , it)
       lr = LogisticRegression(class_weight = cw)
       print('Class weights ', cw)
       lr.fit(X_train,y_train)

       # Save trained model to disk
       name = fname + str(cw[1]) + '.sav'
       pickle.dump(lr, open(name, 'wb'))

       # Predict on validation data
       y_val_pred = lr.predict(X_val)
       print('Performance on validation data - Confusion matrix')
       print(confusion_matrix(y_val,y_val_pred))
   
       precision,recall,fscore,support=score(y_val,y_val_pred,average=None)
       print('Precision, Recall, F-score, Support  on validation data' )
       print("Precision" , precision)
       print("Recall" , recall)
       print("F-score" , fscore)
       print("Support" , support)

       p1 = precision[1]
       r1 = recall[1]
       f1 = fscore[1]

       f.write(str(p1) +','+ str(r1) + ',' + str(f1) + '\n') 
       it += 1

   f.close()

def run():
   filename = 'full_data.csv'
   df = pd.read_csv(filename, usecols = [8,9,10,11,12,13,14] , header = 0)
   
   results = list(map(int, df['Anomaly'])) 
   print('Number of fraudulent transactions ' , sum(results))

   features = ['Transaction_Type', 'Airfare', 'Lodging', 'Meals', 'Other_Transportation', 'Other_Expenses']
   targets = ['Anomaly']

   # Separating out the features and target variables
   X = df.loc[:, features].values
   y = df.loc[:, targets].values

    
   from sklearn.preprocessing import LabelEncoder, OneHotEncoder
   labelencoder_X = LabelEncoder()
   X[:,0] = labelencoder_X.fit_transform(X[:,0])
   onehotencoder = OneHotEncoder(categorical_features = [0])
   x = onehotencoder.fit_transform(X).toarray() 

   scaler = preprocessing.StandardScaler()
   x = scaler.fit_transform(x) 
    
   y  = [i for j in y for i in j]
   
   #Ignore warnings
   warnings.filterwarnings("ignore", category=FutureWarning)

   print("***********Logistic Regression**********")
   logreg(x,y,filename)
  
run()

Number of fraudulent transactions  8213


/home/sandisk/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


***********Logistic Regression**********
**************************************
Iteration number   1
Class weights  {0: 1, 1: 1}
Performance on validation data - Confusion matrix
[[953110     51]
 [   741    491]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99922315 0.90590406]
Recall [0.99994649 0.39853896]
F-score [0.99958469 0.5535513 ]
Support [953161   1232]
**************************************
Iteration number   2
Class weights  {0: 1, 1: 2}
Performance on validation data - Confusion matrix
[[953044    117]
 [   662    570]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99930587 0.82969432]
Recall [0.99987725 0.46266234]
F-score [0.99959148 0.59405941]
Support [953161   1232]
**************************************
Iteration number   3
Class weights  {0: 1, 1: 3}
Performance on validation data - Confusion matrix
[[952973    188]
 [   628    604]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99934144 0.762626

Performance on validation data - Confusion matrix
[[951474   1687]
 [   418    814]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99956087 0.32546981]
Recall [0.9982301  0.66071429]
F-score [0.99889504 0.43611037]
Support [953161   1232]
**************************************
Iteration number   25
Class weights  {0: 1, 1: 25}
Performance on validation data - Confusion matrix
[[951381   1780]
 [   413    819]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99956608 0.3151212 ]
Recall [0.99813253 0.66477273]
F-score [0.99884879 0.4275646 ]
Support [953161   1232]
**************************************
Iteration number   26
Class weights  {0: 1, 1: 26}
Performance on validation data - Confusion matrix
[[951288   1873]
 [   407    825]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99957234 0.30578206]
Recall [0.99803496 0.66964286]
F-score [0.99880306 0.41984733]
Support [953161   1232]
**********************************

Performance on validation data - Confusion matrix
[[949411   3750]
 [   352    880]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99962938 0.19006479]
Recall [0.99606572 0.71428571]
F-score [0.99784437 0.30023883]
Support [953161   1232]
**************************************
Iteration number   49
Class weights  {0: 1, 1: 49}
Performance on validation data - Confusion matrix
[[949316   3845]
 [   351    881]]
Precision, Recall, F-score, Support  on validation data
Precision [0.9996304  0.18641557]
Recall [0.99596605 0.7150974 ]
F-score [0.99779486 0.29573682]
Support [953161   1232]
**************************************
Iteration number   50
Class weights  {0: 1, 1: 50}
Performance on validation data - Confusion matrix
[[949219   3942]
 [   349    883]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99963246 0.18300518]
Recall [0.99586429 0.71672078]
F-score [0.99774482 0.29156348]
Support [953161   1232]
**********************************

Performance on validation data - Confusion matrix
[[947007   6154]
 [   311    921]]
Precision, Recall, F-score, Support  on validation data
Precision [0.9996717  0.13017668]
Recall [0.99354359 0.74756494]
F-score [0.99659823 0.2217407 ]
Support [953161   1232]
**************************************
Iteration number   73
Class weights  {0: 1, 1: 73}
Performance on validation data - Confusion matrix
[[946921   6240]
 [   308    924]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99967484 0.12897822]
Recall [0.99345336 0.75      ]
F-score [0.99655439 0.22010481]
Support [953161   1232]
**************************************
Iteration number   74
Class weights  {0: 1, 1: 74}
Performance on validation data - Confusion matrix
[[946845   6316]
 [   306    926]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99967693 0.12786523]
Recall [0.99337363 0.75162338]
F-score [0.99651531 0.21855086]
Support [953161   1232]
**********************************

Performance on validation data - Confusion matrix
[[944921   8240]
 [   273    959]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99971117 0.10425046]
Recall [0.99135508 0.77840909]
F-score [0.99551559 0.18387499]
Support [953161   1232]
**************************************
Iteration number   97
Class weights  {0: 1, 1: 97}
Performance on validation data - Confusion matrix
[[944835   8326]
 [   272    960]]
Precision, Recall, F-score, Support  on validation data
Precision [0.9997122  0.10338143]
Recall [0.99126485 0.77922078]
F-score [0.99547061 0.18254421]
Support [953161   1232]
**************************************
Iteration number   98
Class weights  {0: 1, 1: 98}
Performance on validation data - Confusion matrix
[[944730   8431]
 [   272    960]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99971217 0.10222554]
Recall [0.99115469 0.77922078]
F-score [0.99541504 0.1807399 ]
Support [953161   1232]
**********************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99974343 0.08867789]
Recall [0.98932604 0.80357143]
F-score [0.99450746 0.15972894]
Support [953161   1232]
**************************************
Iteration number   120
Class weights  {0: 1, 1: 120}
Performance on validation data - Confusion matrix
[[942894  10267]
 [   239    993]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99974659 0.08818828]
Recall [0.98922847 0.80600649]
F-score [0.99445972 0.15898175]
Support [953161   1232]
**************************************
Iteration number   121
Class weights  {0: 1, 1: 121}
Performance on validation data - Confusion matrix
[[942820  10341]
 [   238    994]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99974763 0.08769299]
Recall [0.98915084 0.80681818]
F-score [0.994421   0.15819209]
Support [953161   1232]
**************************************
Iteration number   122
Class weights  {0: 1, 1: 122}
Performance on validati

Performance on validation data - Confusion matrix
[[941042  12119]
 [   213   1019]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99977371 0.07756127]
Recall [0.98728546 0.82711039]
F-score [0.99349034 0.14182324]
Support [953161   1232]
**************************************
Iteration number   144
Class weights  {0: 1, 1: 144}
Performance on validation data - Confusion matrix
[[940971  12190]
 [   213   1019]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99977369 0.07714437]
Recall [0.98721097 0.82711039]
F-score [0.99345262 0.14112596]
Support [953161   1232]
**************************************
Iteration number   145
Class weights  {0: 1, 1: 145}
Performance on validation data - Confusion matrix
[[940894  12267]
 [   212   1020]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99977473 0.07676676]
Recall [0.98713019 0.82792208]
F-score [0.99341223 0.14050554]
Support [953161   1232]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99978815 0.06872006]
Recall [0.98531308 0.83847403]
F-score [0.99249784 0.12702902]
Support [953161   1232]
**************************************
Iteration number   167
Class weights  {0: 1, 1: 167}
Performance on validation data - Confusion matrix
[[939070  14091]
 [   198   1034]]
Precision, Recall, F-score, Support  on validation data
Precision [0.9997892  0.06836364]
Recall [0.98521656 0.83928571]
F-score [0.99244939 0.12642905]
Support [953161   1232]
**************************************
Iteration number   168
Class weights  {0: 1, 1: 168}
Performance on validation data - Confusion matrix
[[938985  14176]
 [   198   1034]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99978918 0.06798159]
Recall [0.98512738 0.83928571]
F-score [0.99240413 0.12577545]
Support [953161   1232]
**************************************
Iteration number   169
Class weights  {0: 1, 1: 169}
Performance on validati

Performance on validation data - Confusion matrix
[[937210  15951]
 [   180   1052]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99980798 0.06187143]
Recall [0.98326516 0.8538961 ]
F-score [0.99146757 0.11538251]
Support [953161   1232]
**************************************
Iteration number   191
Class weights  {0: 1, 1: 191}
Performance on validation data - Confusion matrix
[[937129  16032]
 [   180   1052]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99980796 0.06157808]
Recall [0.98318018 0.8538961 ]
F-score [0.99142435 0.11487224]
Support [953161   1232]
**************************************
Iteration number   192
Class weights  {0: 1, 1: 192}
Performance on validation data - Confusion matrix
[[937042  16119]
 [   180   1052]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99980794 0.06126609]
Recall [0.9830889 0.8538961]
F-score [0.99137794 0.11432919]
Support [953161   1232]
********************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99982151 0.05673948]
Recall [0.98142496 0.86444805]
F-score [0.99053783 0.10648935]
Support [953161   1232]
**************************************
Iteration number   214
Class weights  {0: 1, 1: 214}
Performance on validation data - Confusion matrix
[[935392  17769]
 [   167   1065]]
Precision, Recall, F-score, Support  on validation data
Precision [0.9998215  0.05654667]
Recall [0.98135782 0.86444805]
F-score [0.99050362 0.10614971]
Support [953161   1232]
**************************************
Iteration number   215
Class weights  {0: 1, 1: 215}
Performance on validation data - Confusion matrix
[[935321  17840]
 [   167   1065]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99982148 0.0563343 ]
Recall [0.98128333 0.86444805]
F-score [0.99046567 0.10577544]
Support [953161   1232]
**************************************
Iteration number   216
Class weights  {0: 1, 1: 216}
Performance on validati

Performance on validation data - Confusion matrix
[[933590  19571]
 [   160   1072]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99982865 0.05193044]
Recall [0.97946727 0.87012987]
F-score [0.98954323 0.09801143]
Support [953161   1232]
**************************************
Iteration number   238
Class weights  {0: 1, 1: 238}
Performance on validation data - Confusion matrix
[[933516  19645]
 [   159   1073]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99982971 0.05179071]
Recall [0.97938963 0.87094156]
F-score [0.98950412 0.09776765]
Support [953161   1232]
**************************************
Iteration number   239
Class weights  {0: 1, 1: 239}
Performance on validation data - Confusion matrix
[[933434  19727]
 [   158   1074]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99983076 0.05163213]
Recall [0.9793036  0.87175325]
F-score [0.98946073 0.09749013]
Support [953161   1232]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99983261 0.04801214]
Recall [0.97761658 0.87337662]
F-score [0.9885998 0.0910206]
Support [953161   1232]
**************************************
Iteration number   261
Class weights  {0: 1, 1: 261}
Performance on validation data - Confusion matrix
[[931757  21404]
 [   156   1076]]
Precision, Recall, F-score, Support  on validation data
Precision [0.9998326  0.04786477]
Recall [0.97754419 0.87337662]
F-score [0.98856278 0.09075574]
Support [953161   1232]
**************************************
Iteration number   262
Class weights  {0: 1, 1: 262}
Performance on validation data - Confusion matrix
[[931702  21459]
 [   156   1076]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99983259 0.04774795]
Recall [0.97748649 0.87337662]
F-score [0.98853327 0.09054571]
Support [953161   1232]
**************************************
Iteration number   263
Class weights  {0: 1, 1: 263}
Performance on validation

Performance on validation data - Confusion matrix
[[930170  22991]
 [   152   1080]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99983662 0.04486727]
Recall [0.97587921 0.87662338]
F-score [0.98771266 0.08536537]
Support [953161   1232]
**************************************
Iteration number   285
Class weights  {0: 1, 1: 285}
Performance on validation data - Confusion matrix
[[930097  23064]
 [   152   1080]]
Precision, Recall, F-score, Support  on validation data
Precision [0.9998366  0.04473161]
Recall [0.97580262 0.87662338]
F-score [0.98767342 0.0851198 ]
Support [953161   1232]
**************************************
Iteration number   286
Class weights  {0: 1, 1: 286}
Performance on validation data - Confusion matrix
[[930030  23131]
 [   152   1080]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99983659 0.04460782]
Recall [0.97573233 0.87662338]
F-score [0.98763741 0.08489565]
Support [953161   1232]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.9998428  0.04232268]
Recall [0.97421842 0.88149351]
F-score [0.9868643  0.08076751]
Support [953161   1232]
**************************************
Iteration number   308
Class weights  {0: 1, 1: 308}
Performance on validation data - Confusion matrix
[[928526  24635]
 [   146   1086]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99984279 0.04222231]
Recall [0.97415442 0.88149351]
F-score [0.98683146 0.08058472]
Support [953161   1232]
**************************************
Iteration number   309
Class weights  {0: 1, 1: 309}
Performance on validation data - Confusion matrix
[[928480  24681]
 [   146   1086]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99984278 0.04214693]
Recall [0.97410616 0.88149351]
F-score [0.98680669 0.08044742]
Support [953161   1232]
**************************************
Iteration number   310
Class weights  {0: 1, 1: 310}
Performance on validati

Performance on validation data - Confusion matrix
[[926983  26178]
 [   144   1088]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99984468 0.03990318]
Recall [0.97253559 0.88311688]
F-score [0.98600108 0.07635624]
Support [953161   1232]
**************************************
Iteration number   332
Class weights  {0: 1, 1: 332}
Performance on validation data - Confusion matrix
[[926914  26247]
 [   144   1088]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99984467 0.03980245]
Recall [0.9724632  0.88311688]
F-score [0.98596387 0.07617181]
Support [953161   1232]
**************************************
Iteration number   333
Class weights  {0: 1, 1: 333}
Performance on validation data - Confusion matrix
[[926861  26300]
 [   144   1088]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99984466 0.03972543]
Recall [0.9724076  0.88311688]
F-score [0.98593528 0.07603075]
Support [953161   1232]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.999852   0.03811878]
Recall [0.97101119 0.8887987 ]
F-score [0.98522057 0.07310234]
Support [953161   1232]
**************************************
Iteration number   355
Class weights  {0: 1, 1: 355}
Performance on validation data - Confusion matrix
[[925465  27696]
 [   136   1096]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99985307 0.03806613]
Recall [0.970943   0.88961039]
F-score [0.98518599 0.07300826]
Support [953161   1232]
**************************************
Iteration number   356
Class weights  {0: 1, 1: 356}
Performance on validation data - Confusion matrix
[[925404  27757]
 [   136   1096]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99985306 0.03798565]
Recall [0.970879   0.88961039]
F-score [0.98515304 0.07286023]
Support [953161   1232]
**************************************
Iteration number   357
Class weights  {0: 1, 1: 357}
Performance on validati

Performance on validation data - Confusion matrix
[[923975  29186]
 [   135   1097]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99985391 0.03622494]
Recall [0.96937978 0.89042208]
F-score [0.98438105 0.06961764]
Support [953161   1232]
**************************************
Iteration number   379
Class weights  {0: 1, 1: 379}
Performance on validation data - Confusion matrix
[[923906  29255]
 [   135   1097]]
Precision, Recall, F-score, Support  on validation data
Precision [0.9998539  0.03614259]
Recall [0.96930739 0.89042208]
F-score [0.98434372 0.06946555]
Support [953161   1232]
**************************************
Iteration number   380
Class weights  {0: 1, 1: 380}
Performance on validation data - Confusion matrix
[[923833  29328]
 [   135   1097]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99985389 0.03605588]
Recall [0.9692308  0.89042208]
F-score [0.98430422 0.06930537]
Support [953161   1232]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99985585 0.0346229 ]
Recall [0.96785118 0.89204545]
F-score [0.98359324 0.06665858]
Support [953161   1232]
**************************************
Iteration number   402
Class weights  {0: 1, 1: 402}
Performance on validation data - Confusion matrix
[[922449  30712]
 [   133   1099]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99985584 0.0345478 ]
Recall [0.96777879 0.89204545]
F-score [0.98355585 0.06651938]
Support [953161   1232]
**************************************
Iteration number   403
Class weights  {0: 1, 1: 403}
Performance on validation data - Confusion matrix
[[922388  30773]
 [   133   1099]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99985583 0.03448168]
Recall [0.96771479 0.89204545]
F-score [0.98352279 0.06639681]
Support [953161   1232]
**************************************
Iteration number   404
Class weights  {0: 1, 1: 404}
Performance on validati

Performance on validation data - Confusion matrix
[[921038  32123]
 [   126   1106]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99986322 0.03328418]
Recall [0.96629845 0.89772727]
F-score [0.98279434 0.0641885 ]
Support [953161   1232]
**************************************
Iteration number   426
Class weights  {0: 1, 1: 426}
Performance on validation data - Confusion matrix
[[920992  32169]
 [   126   1106]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99986321 0.03323817]
Recall [0.96625019 0.89772727]
F-score [0.98276937 0.06410294]
Support [953161   1232]
**************************************
Iteration number   427
Class weights  {0: 1, 1: 427}
Performance on validation data - Confusion matrix
[[920929  32232]
 [   126   1106]]
Precision, Recall, F-score, Support  on validation data
Precision [0.9998632  0.03317536]
Recall [0.9661841  0.89772727]
F-score [0.98273518 0.06398612]
Support [953161   1232]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99986954 0.03214244]
Recall [0.96487057 0.9025974 ]
F-score [0.98205833 0.06207436]
Support [953161   1232]
**************************************
Iteration number   449
Class weights  {0: 1, 1: 449}
Performance on validation data - Confusion matrix
[[919631  33530]
 [   120   1112]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99986953 0.03209976]
Recall [0.96482231 0.9025974 ]
F-score [0.98203333 0.06199476]
Support [953161   1232]
**************************************
Iteration number   450
Class weights  {0: 1, 1: 450}
Performance on validation data - Confusion matrix
[[919566  33595]
 [   120   1112]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99986952 0.03203965]
Recall [0.96475412 0.9025974 ]
F-score [0.981998   0.06188263]
Support [953161   1232]
**************************************
Iteration number   451
Class weights  {0: 1, 1: 451}
Performance on validati

Performance on validation data - Confusion matrix
[[918271  34890]
 [   117   1115]]
Precision, Recall, F-score, Support  on validation data
Precision [0.9998726  0.03096792]
Recall [0.96339548 0.90503247]
F-score [0.98129517 0.05988667]
Support [953161   1232]
**************************************
Iteration number   473
Class weights  {0: 1, 1: 473}
Performance on validation data - Confusion matrix
[[918212  34949]
 [   117   1115]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99987259 0.03091726]
Recall [0.96333358 0.90503247]
F-score [0.98126306 0.05979193]
Support [953161   1232]
**************************************
Iteration number   474
Class weights  {0: 1, 1: 474}
Performance on validation data - Confusion matrix
[[918136  35025]
 [   117   1115]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99987258 0.03085224]
Recall [0.96325385 0.90503247]
F-score [0.98122169 0.05967034]
Support [953161   1232]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99988223 0.03008887]
Recall [0.96198753 0.91233766]
F-score [0.9805689  0.05825645]
Support [953161   1232]
**************************************
Iteration number   496
Class weights  {0: 1, 1: 496}
Performance on validation data - Confusion matrix
[[916883  36278]
 [   107   1125]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99988331 0.0300778 ]
Recall [0.96193927 0.91314935]
F-score [0.98054435 0.05823735]
Support [953161   1232]
**************************************
Iteration number   497
Class weights  {0: 1, 1: 497}
Performance on validation data - Confusion matrix
[[916824  36337]
 [   106   1126]]
Precision, Recall, F-score, Support  on validation data
Precision [0.9998844  0.03005632]
Recall [0.96187737 0.91396104]
F-score [0.98051271 0.05819873]
Support [953161   1232]
**************************************
Iteration number   498
Class weights  {0: 1, 1: 498}
Performance on validati