In [3]:
import numpy as np
import pandas as pd
import csv
import sys
import os
  
import matplotlib.pyplot as plt

from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
import warnings
import pickle

from sklearn.ensemble import RandomForestClassifier

max_iters = 501
#n_estimators = 10

def rfc(x,y,filename):

   # Model output file name
   file = (os.path.splitext(filename))[0]
   fname = './models/rfc_' + file +'/'

   # File for writing precision,recall, f-measure scores for fraud transactions
   f = open('./prf/rfc_'+ file + '_prf' +'.txt' ,'w')
   f.write('precision,recall,f-score \n')

   # Stratified sampling based on Y
   X_train, X_test, y_train, y_test = train_test_split(x, y,stratify=y , test_size=0.30, random_state=42)

   # Create 15% validation set and 15% test set split
   X_val, X_test, y_val, y_test = train_test_split(X_test, y_test,stratify=y_test , test_size=0.50, random_state=42)
   
   #Iterations
   it = 1
   
   # Run training algorithm for multiple class weights
   while it < max_iters:
       cw = {}
       cw[0] = 1
       cw[1] = it
       # Train
       print('**************************************')
       print("Iteration number  " , it)
       rfc = RandomForestClassifier(n_jobs=2, random_state=0, class_weight = cw)
       #lr = LogisticRegression(class_weight = cw)
       print('Class weights ', cw)
       rfc.fit(X_train,y_train)

       # Save trained model to disk
       name = fname + str(cw[1]) + '.sav'
       pickle.dump(rfc, open(name, 'wb'))

       # Predict on validation data
       y_val_pred = rfc.predict(X_val)
       print('Performance on validation data - Confusion matrix')
       print(confusion_matrix(y_val,y_val_pred))
   
       precision,recall,fscore,support=score(y_val,y_val_pred,average=None)
       print('Precision, Recall, F-score, Support  on validation data' )
       print("Precision" , precision)
       print("Recall" , recall)
       print("F-score" , fscore)
       print("Support" , support)

       p1 = precision[1]
       r1 = recall[1]
       f1 = fscore[1]

       f.write(str(p1) +','+ str(r1) + ',' + str(f1) + '\n') 
       it += 1

   f.close()

def run():
   filename = 'm2.csv'
   df = pd.read_csv(filename, usecols = [9,10,11,12,13,14] , header = 0)
   
   results = list(map(int, df['Anomaly'])) 
   print('Number of fraudulent transactions ' , sum(results))

   features = ['Airfare', 'Lodging', 'Meals', 'Other_Transportation', 'Other_Expenses']
   targets = ['Anomaly']

   # Separating out the features and target variables
   x = df.loc[:, features].values
   y = df.loc[:, targets].values
    
   scaler = preprocessing.StandardScaler()
   x = scaler.fit_transform(x)    

   y  = [i for j in y for i in j]
   
   #Ignore warnings
   warnings.filterwarnings("ignore", category=FutureWarning)

   print("***********Logistic Regression**********")
   rfc(x,y,filename)
  
run()

Number of fraudulent transactions  4116
***********Logistic Regression**********
**************************************
Iteration number   1
Class weights  {0: 1, 1: 1}
Performance on validation data - Confusion matrix
[[334975     32]
 [   290    328]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99913501 0.91111111]
Recall [0.99990448 0.53074434]
F-score [0.9995196  0.67075665]
Support [335007    618]
**************************************
Iteration number   2
Class weights  {0: 1, 1: 2}
Performance on validation data - Confusion matrix
[[334969     38]
 [   282    336]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99915884 0.89839572]
Recall [0.99988657 0.54368932]
F-score [0.99952257 0.67741935]
Support [335007    618]
**************************************
Iteration number   3
Class weights  {0: 1, 1: 3}
Performance on validation data - Confusion matrix
[[334970     37]
 [   287    331]]
Precision, Recall, F-score, Support  on valida

Performance on validation data - Confusion matrix
[[334966     41]
 [   278    340]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99917075 0.89238845]
Recall [0.99987761 0.55016181]
F-score [0.99952406 0.68068068]
Support [335007    618]
**************************************
Iteration number   25
Class weights  {0: 1, 1: 25}
Performance on validation data - Confusion matrix
[[334968     39]
 [   286    332]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99914692 0.89487871]
Recall [0.99988358 0.53721683]
F-score [0.99951511 0.67138524]
Support [335007    618]
**************************************
Iteration number   26
Class weights  {0: 1, 1: 26}
Performance on validation data - Confusion matrix
[[334971     36]
 [   288    330]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99914096 0.90163934]
Recall [0.99989254 0.53398058]
F-score [0.99951661 0.67073171]
Support [335007    618]
**********************************

Performance on validation data - Confusion matrix
[[334975     32]
 [   277    341]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99917376 0.91420912]
Recall [0.99990448 0.55177994]
F-score [0.99953898 0.68819374]
Support [335007    618]
**************************************
Iteration number   49
Class weights  {0: 1, 1: 49}
Performance on validation data - Confusion matrix
[[334969     38]
 [   278    340]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99917076 0.8994709 ]
Recall [0.99988657 0.55016181]
F-score [0.99952854 0.68273092]
Support [335007    618]
**************************************
Iteration number   50
Class weights  {0: 1, 1: 50}
Performance on validation data - Confusion matrix
[[334965     42]
 [   282    336]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99915883 0.88888889]
Recall [0.99987463 0.54368932]
F-score [0.9995166 0.6746988]
Support [335007    618]
************************************

Performance on validation data - Confusion matrix
[[334973     34]
 [   281    337]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99916183 0.9083558 ]
Recall [0.99989851 0.54530744]
F-score [0.99953003 0.68149646]
Support [335007    618]
**************************************
Iteration number   73
Class weights  {0: 1, 1: 73}
Performance on validation data - Confusion matrix
[[334965     42]
 [   285    333]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99914989 0.888     ]
Recall [0.99987463 0.53883495]
F-score [0.99951213 0.67069486]
Support [335007    618]
**************************************
Iteration number   74
Class weights  {0: 1, 1: 74}
Performance on validation data - Confusion matrix
[[334968     39]
 [   288    330]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99914095 0.89430894]
Recall [0.99988358 0.53398058]
F-score [0.99951213 0.66869301]
Support [335007    618]
**********************************

Performance on validation data - Confusion matrix
[[334973     34]
 [   277    341]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99917375 0.90933333]
Recall [0.99989851 0.55177994]
F-score [0.999536   0.68680765]
Support [335007    618]
**************************************
Iteration number   97
Class weights  {0: 1, 1: 97}
Performance on validation data - Confusion matrix
[[334964     43]
 [   270    348]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99919459 0.89002558]
Recall [0.99987164 0.5631068 ]
F-score [0.999533   0.68979187]
Support [335007    618]
**************************************
Iteration number   98
Class weights  {0: 1, 1: 98}
Performance on validation data - Confusion matrix
[[334977     30]
 [   280    338]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99916482 0.91847826]
Recall [0.99991045 0.54692557]
F-score [0.9995375  0.68559838]
Support [335007    618]
**********************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99915288 0.9027027 ]
Recall [0.99989254 0.54045307]
F-score [0.99952257 0.67611336]
Support [335007    618]
**************************************
Iteration number   120
Class weights  {0: 1, 1: 120}
Performance on validation data - Confusion matrix
[[334968     39]
 [   282    336]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99915884 0.896     ]
Recall [0.99988358 0.54368932]
F-score [0.99952108 0.67673716]
Support [335007    618]
**************************************
Iteration number   121
Class weights  {0: 1, 1: 121}
Performance on validation data - Confusion matrix
[[334972     35]
 [   289    329]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99913799 0.90384615]
Recall [0.99989552 0.53236246]
F-score [0.99951661 0.6700611 ]
Support [335007    618]
**************************************
Iteration number   122
Class weights  {0: 1, 1: 122}
Performance on validati

Performance on validation data - Confusion matrix
[[334976     31]
 [   274    344]]
Precision, Recall, F-score, Support  on validation data
Precision [0.9991827  0.91733333]
Recall [0.99990746 0.5566343 ]
F-score [0.99954495 0.69284995]
Support [335007    618]
**************************************
Iteration number   144
Class weights  {0: 1, 1: 144}
Performance on validation data - Confusion matrix
[[334976     31]
 [   274    344]]
Precision, Recall, F-score, Support  on validation data
Precision [0.9991827  0.91733333]
Recall [0.99990746 0.5566343 ]
F-score [0.99954495 0.69284995]
Support [335007    618]
**************************************
Iteration number   145
Class weights  {0: 1, 1: 145}
Performance on validation data - Confusion matrix
[[334973     34]
 [   274    344]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99918269 0.91005291]
Recall [0.99989851 0.5566343 ]
F-score [0.99954047 0.69076305]
Support [335007    618]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99914394 0.90190736]
Recall [0.99989254 0.53559871]
F-score [0.9995181  0.67208122]
Support [335007    618]
**************************************
Iteration number   167
Class weights  {0: 1, 1: 167}
Performance on validation data - Confusion matrix
[[334967     40]
 [   286    332]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99914691 0.89247312]
Recall [0.9998806  0.53721683]
F-score [0.99951362 0.67070707]
Support [335007    618]
**************************************
Iteration number   168
Class weights  {0: 1, 1: 168}
Performance on validation data - Confusion matrix
[[334972     35]
 [   284    334]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99915289 0.90514905]
Recall [0.99989552 0.54045307]
F-score [0.99952407 0.67679838]
Support [335007    618]
**************************************
Iteration number   169
Class weights  {0: 1, 1: 169}
Performance on validati

Performance on validation data - Confusion matrix
[[334972     35]
 [   283    335]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99915587 0.90540541]
Recall [0.99989552 0.5420712 ]
F-score [0.99952556 0.67813765]
Support [335007    618]
**************************************
Iteration number   191
Class weights  {0: 1, 1: 191}
Performance on validation data - Confusion matrix
[[334974     33]
 [   283    335]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99915587 0.91032609]
Recall [0.99990149 0.5420712 ]
F-score [0.99952854 0.67951318]
Support [335007    618]
**************************************
Iteration number   192
Class weights  {0: 1, 1: 192}
Performance on validation data - Confusion matrix
[[334974     33]
 [   283    335]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99915587 0.91032609]
Recall [0.99990149 0.5420712 ]
F-score [0.99952854 0.67951318]
Support [335007    618]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99916479 0.89417989]
Recall [0.9998806  0.54692557]
F-score [0.99952257 0.67871486]
Support [335007    618]
**************************************
Iteration number   214
Class weights  {0: 1, 1: 214}
Performance on validation data - Confusion matrix
[[334971     36]
 [   288    330]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99914096 0.90163934]
Recall [0.99989254 0.53398058]
F-score [0.99951661 0.67073171]
Support [335007    618]
**************************************
Iteration number   215
Class weights  {0: 1, 1: 215}
Performance on validation data - Confusion matrix
[[334972     35]
 [   290    328]]
Precision, Recall, F-score, Support  on validation data
Precision [0.999135   0.90358127]
Recall [0.99989552 0.53074434]
F-score [0.99951512 0.6687054 ]
Support [335007    618]
**************************************
Iteration number   216
Class weights  {0: 1, 1: 216}
Performance on validati

Performance on validation data - Confusion matrix
[[334976     31]
 [   281    337]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99916184 0.91576087]
Recall [0.99990746 0.54530744]
F-score [0.99953451 0.68356998]
Support [335007    618]
**************************************
Iteration number   238
Class weights  {0: 1, 1: 238}
Performance on validation data - Confusion matrix
[[334972     35]
 [   281    337]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99916183 0.90591398]
Recall [0.99989552 0.54530744]
F-score [0.99952854 0.68080808]
Support [335007    618]
**************************************
Iteration number   239
Class weights  {0: 1, 1: 239}
Performance on validation data - Confusion matrix
[[334972     35]
 [   281    337]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99916183 0.90591398]
Recall [0.99989552 0.54530744]
F-score [0.99952854 0.68080808]
Support [335007    618]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99914097 0.90410959]
Recall [0.99989552 0.53398058]
F-score [0.9995181  0.67141404]
Support [335007    618]
**************************************
Iteration number   261
Class weights  {0: 1, 1: 261}
Performance on validation data - Confusion matrix
[[334973     34]
 [   288    330]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99914097 0.90659341]
Recall [0.99989851 0.53398058]
F-score [0.9995196  0.67209776]
Support [335007    618]
**************************************
Iteration number   262
Class weights  {0: 1, 1: 262}
Performance on validation data - Confusion matrix
[[334970     37]
 [   282    336]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99915884 0.90080429]
Recall [0.99988955 0.54368932]
F-score [0.99952406 0.67810293]
Support [335007    618]
**************************************
Iteration number   263
Class weights  {0: 1, 1: 263}
Performance on validati

Performance on validation data - Confusion matrix
[[334967     40]
 [   282    336]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99915883 0.89361702]
Recall [0.9998806  0.54368932]
F-score [0.99951959 0.67605634]
Support [335007    618]
**************************************
Iteration number   285
Class weights  {0: 1, 1: 285}
Performance on validation data - Confusion matrix
[[334967     40]
 [   282    336]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99915883 0.89361702]
Recall [0.9998806  0.54368932]
F-score [0.99951959 0.67605634]
Support [335007    618]
**************************************
Iteration number   286
Class weights  {0: 1, 1: 286}
Performance on validation data - Confusion matrix
[[334969     38]
 [   287    331]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99914394 0.89701897]
Recall [0.99988657 0.53559871]
F-score [0.99951512 0.67071935]
Support [335007    618]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99917077 0.90909091]
Recall [0.99989851 0.55016181]
F-score [0.99953451 0.68548387]
Support [335007    618]
**************************************
Iteration number   308
Class weights  {0: 1, 1: 308}
Performance on validation data - Confusion matrix
[[334973     34]
 [   278    340]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99917077 0.90909091]
Recall [0.99989851 0.55016181]
F-score [0.99953451 0.68548387]
Support [335007    618]
**************************************
Iteration number   309
Class weights  {0: 1, 1: 309}
Performance on validation data - Confusion matrix
[[334969     38]
 [   278    340]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99917076 0.8994709 ]
Recall [0.99988657 0.55016181]
F-score [0.99952854 0.68273092]
Support [335007    618]
**************************************
Iteration number   310
Class weights  {0: 1, 1: 310}
Performance on validati

Performance on validation data - Confusion matrix
[[334968     39]
 [   276    342]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99917672 0.8976378 ]
Recall [0.99988358 0.55339806]
F-score [0.99953003 0.68468468]
Support [335007    618]
**************************************
Iteration number   332
Class weights  {0: 1, 1: 332}
Performance on validation data - Confusion matrix
[[334961     46]
 [   284    334]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99915286 0.87894737]
Recall [0.99986269 0.54045307]
F-score [0.99950765 0.66933868]
Support [335007    618]
**************************************
Iteration number   333
Class weights  {0: 1, 1: 333}
Performance on validation data - Confusion matrix
[[334961     46]
 [   284    334]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99915286 0.87894737]
Recall [0.99986269 0.54045307]
F-score [0.99950765 0.66933868]
Support [335007    618]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99914097 0.90909091]
Recall [0.99990149 0.53398058]
F-score [0.99952109 0.67278287]
Support [335007    618]
**************************************
Iteration number   355
Class weights  {0: 1, 1: 355}
Performance on validation data - Confusion matrix
[[334974     33]
 [   288    330]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99914097 0.90909091]
Recall [0.99990149 0.53398058]
F-score [0.99952109 0.67278287]
Support [335007    618]
**************************************
Iteration number   356
Class weights  {0: 1, 1: 356}
Performance on validation data - Confusion matrix
[[334972     35]
 [   288    330]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99914097 0.90410959]
Recall [0.99989552 0.53398058]
F-score [0.9995181  0.67141404]
Support [335007    618]
**************************************
Iteration number   357
Class weights  {0: 1, 1: 357}
Performance on validati

Performance on validation data - Confusion matrix
[[334970     37]
 [   283    335]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99915586 0.90053763]
Recall [0.99988955 0.5420712 ]
F-score [0.99952257 0.67676768]
Support [335007    618]
**************************************
Iteration number   379
Class weights  {0: 1, 1: 379}
Performance on validation data - Confusion matrix
[[334971     36]
 [   281    337]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99916182 0.90348525]
Recall [0.99989254 0.54530744]
F-score [0.99952705 0.68012109]
Support [335007    618]
**************************************
Iteration number   380
Class weights  {0: 1, 1: 380}
Performance on validation data - Confusion matrix
[[334973     34]
 [   282    336]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99915885 0.90810811]
Recall [0.99989851 0.54368932]
F-score [0.99952854 0.68016194]
Support [335007    618]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99912905 0.90555556]
Recall [0.99989851 0.52750809]
F-score [0.99951363 0.66666667]
Support [335007    618]
**************************************
Iteration number   402
Class weights  {0: 1, 1: 402}
Performance on validation data - Confusion matrix
[[334972     35]
 [   289    329]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99913799 0.90384615]
Recall [0.99989552 0.53236246]
F-score [0.99951661 0.6700611 ]
Support [335007    618]
**************************************
Iteration number   403
Class weights  {0: 1, 1: 403}
Performance on validation data - Confusion matrix
[[334972     35]
 [   289    329]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99913799 0.90384615]
Recall [0.99989552 0.53236246]
F-score [0.99951661 0.6700611 ]
Support [335007    618]
**************************************
Iteration number   404
Class weights  {0: 1, 1: 404}
Performance on validati

Performance on validation data - Confusion matrix
[[334972     35]
 [   277    341]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99917375 0.90691489]
Recall [0.99989552 0.55177994]
F-score [0.99953451 0.6861167 ]
Support [335007    618]
**************************************
Iteration number   426
Class weights  {0: 1, 1: 426}
Performance on validation data - Confusion matrix
[[334972     35]
 [   277    341]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99917375 0.90691489]
Recall [0.99989552 0.55177994]
F-score [0.99953451 0.6861167 ]
Support [335007    618]
**************************************
Iteration number   427
Class weights  {0: 1, 1: 427}
Performance on validation data - Confusion matrix
[[334972     35]
 [   277    341]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99917375 0.90691489]
Recall [0.99989552 0.55177994]
F-score [0.99953451 0.6861167 ]
Support [335007    618]
******************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99914392 0.88266667]
Recall [0.99986866 0.53559871]
F-score [0.99950616 0.66666667]
Support [335007    618]
**************************************
Iteration number   449
Class weights  {0: 1, 1: 449}
Performance on validation data - Confusion matrix
[[334967     40]
 [   286    332]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99914691 0.89247312]
Recall [0.9998806  0.53721683]
F-score [0.99951362 0.67070707]
Support [335007    618]
**************************************
Iteration number   450
Class weights  {0: 1, 1: 450}
Performance on validation data - Confusion matrix
[[334967     40]
 [   286    332]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99914691 0.89247312]
Recall [0.9998806  0.53721683]
F-score [0.99951362 0.67070707]
Support [335007    618]
**************************************
Iteration number   451
Class weights  {0: 1, 1: 451}
Performance on validati

Performance on validation data - Confusion matrix
[[334966     41]
 [   288    330]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99914095 0.88948787]
Recall [0.99987761 0.53398058]
F-score [0.99950915 0.66734075]
Support [335007    618]
**************************************
Iteration number   473
Class weights  {0: 1, 1: 473}
Performance on validation data - Confusion matrix
[[334962     45]
 [   286    332]]
Precision, Recall, F-score, Support  on validation data
Precision [0.9991469 0.8806366]
Recall [0.99986567 0.53721683]
F-score [0.99950616 0.66733668]
Support [335007    618]
**************************************
Iteration number   474
Class weights  {0: 1, 1: 474}
Performance on validation data - Confusion matrix
[[334963     44]
 [   282    336]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99915882 0.88421053]
Recall [0.99986866 0.54368932]
F-score [0.99951362 0.67334669]
Support [335007    618]
********************************

Precision, Recall, F-score, Support  on validation data
Precision [0.99915288 0.90026954]
Recall [0.99988955 0.54045307]
F-score [0.99952108 0.67542973]
Support [335007    618]
**************************************
Iteration number   496
Class weights  {0: 1, 1: 496}
Performance on validation data - Confusion matrix
[[334970     37]
 [   284    334]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99915288 0.90026954]
Recall [0.99988955 0.54045307]
F-score [0.99952108 0.67542973]
Support [335007    618]
**************************************
Iteration number   497
Class weights  {0: 1, 1: 497}
Performance on validation data - Confusion matrix
[[334970     37]
 [   284    334]]
Precision, Recall, F-score, Support  on validation data
Precision [0.99915288 0.90026954]
Recall [0.99988955 0.54045307]
F-score [0.99952108 0.67542973]
Support [335007    618]
**************************************
Iteration number   498
Class weights  {0: 1, 1: 498}
Performance on validati