In [2]:
import numpy as np
import pandas as pd
import csv
import sys
import os

import matplotlib.pyplot as plt    
    
from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
import warnings
import pickle

max_iters = 501


def svm(x,y,filename):

   # Model output file name
   file = (os.path.splitext(filename))[0]
   fname = './models/svm_' + file +'/'

   # File for writing precision,recall, f-measure scores for fraud transactions
   f = open('./prf/svm_'+ file + '_prf' +'.txt' ,'w')
   f.write('precision,recall,f-score \n')

   # Stratified sampling based on Y
   X_train, X_test, y_train, y_test = train_test_split(x, y,stratify=y , test_size=0.30, random_state=42)

   # Create 15% validation set and 15% test set split
   X_val, X_test, y_val, y_test = train_test_split(X_test, y_test,stratify=y_test , test_size=0.50, random_state=42)

   #Iterations
   it = 1
   
   # Run training algorithm for multiple class weights
   while it < max_iters:
       cw = {}
       cw[0] = 1
       cw[1] = it
       # Train
       print('**************************************')
       print("Iteration number  " , it)
       svm = LinearSVC(class_weight = cw, dual = False ,tol=1e-05,max_iter = 1000)
       print('Class weights ', cw)
       svm.fit(X_train,y_train)

       # Save trained model to disk
       name = fname + str(cw[1]) + '.sav'
       pickle.dump(svm, open(name, 'wb'))

       #Predict on validation data
       y_val_pred = svm.predict(X_val)
       print('Performance on validation data - Confusion matrix')
       print(confusion_matrix(y_val,y_val_pred))
   
       precision,recall,fscore,support=score(y_val,y_val_pred,average=None)
       print('Precision, Recall, F-score, Support on validation data' )
       print("Precision" , precision)
       print("Recall" , recall)
       print("F-score" , fscore)
       print("Support" , support)

       p1 = precision[1]
       r1 = recall[1]
       f1 = fscore[1]

       f.write(str(p1) +','+ str(r1) + ',' + str(f1) + '\n')    
       it += 1

   f.close()

def run():
   filename = 'full_data.csv'
   df = pd.read_csv(filename, usecols = [8,9,10,11,12,13,14] , header = 0)
   
   results = list(map(int, df['Anomaly'])) 
   print('Number of fraudulent transactions ' , sum(results))

   features = ['Transaction_Type', 'Airfare', 'Lodging', 'Meals', 'Other_Transportation', 'Other_Expenses']
   targets = ['Anomaly']

   # Separating out the features and target variables
   X = df.loc[:, features].values
   y = df.loc[:, targets].values

    
   from sklearn.preprocessing import LabelEncoder, OneHotEncoder
   labelencoder_X = LabelEncoder()
   X[:,0] = labelencoder_X.fit_transform(X[:,0])
   onehotencoder = OneHotEncoder(categorical_features = [0])
   x = onehotencoder.fit_transform(X).toarray() 

   scaler = preprocessing.StandardScaler()
   x = scaler.fit_transform(x) 
    
   y  = [i for j in y for i in j]
   
   #Ignore warnings
   warnings.filterwarnings("ignore", category=FutureWarning)

   print("**************** SVM *******************")
   svm(x,y,filename)
  
run()

Number of fraudulent transactions  8213


/home/sandisk/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


**************** SVM *******************
**************************************
Iteration number   1
Class weights  {0: 1, 1: 1}
Performance on validation data - Confusion matrix
[[953142     19]
 [   810    422]]
Precision, Recall, F-score, Support on validation data
Precision [0.9991509 0.9569161]
Recall [0.99998007 0.34253247]
F-score [0.99956531 0.50448296]
Support [953161   1232]
**************************************
Iteration number   2
Class weights  {0: 1, 1: 2}
Performance on validation data - Confusion matrix
[[953123     38]
 [   751    481]]
Precision, Recall, F-score, Support on validation data
Precision [0.99921268 0.92678227]
Recall [0.99996013 0.39042208]
F-score [0.99958627 0.54940034]
Support [953161   1232]
**************************************
Iteration number   3
Class weights  {0: 1, 1: 3}
Performance on validation data - Confusion matrix
[[953088     73]
 [   705    527]]
Precision, Recall, F-score, Support on validation data
Precision [0.99926085 0.87833333]
R

[[951961   1200]
 [   504    728]]
Precision, Recall, F-score, Support on validation data
Precision [0.99947085 0.37759336]
Recall [0.99874103 0.59090909]
F-score [0.99910581 0.46075949]
Support [953161   1232]
**************************************
Iteration number   25
Class weights  {0: 1, 1: 25}
Performance on validation data - Confusion matrix
[[951886   1275]
 [   497    735]]
Precision, Recall, F-score, Support on validation data
Precision [0.99947815 0.36567164]
Recall [0.99866235 0.59659091]
F-score [0.99907008 0.45342381]
Support [953161   1232]
**************************************
Iteration number   26
Class weights  {0: 1, 1: 26}
Performance on validation data - Confusion matrix
[[951821   1340]
 [   489    743]]
Precision, Recall, F-score, Support on validation data
Precision [0.99948651 0.35669707]
Recall [0.99859415 0.60308442]
F-score [0.99904013 0.44826546]
Support [953161   1232]
**************************************
Iteration number   27
Class weights  {0: 1, 1: 2

Performance on validation data - Confusion matrix
[[950251   2910]
 [   413    819]]
Precision, Recall, F-score, Support on validation data
Precision [0.99956557 0.21962993]
Recall [0.996947   0.66477273]
F-score [0.99825457 0.33017537]
Support [953161   1232]
**************************************
Iteration number   49
Class weights  {0: 1, 1: 49}
Performance on validation data - Confusion matrix
[[950197   2964]
 [   413    819]]
Precision, Recall, F-score, Support on validation data
Precision [0.99956554 0.21649485]
Recall [0.99689035 0.66477273]
F-score [0.99822615 0.32662014]
Support [953161   1232]
**************************************
Iteration number   50
Class weights  {0: 1, 1: 50}
Performance on validation data - Confusion matrix
[[950120   3041]
 [   411    821]]
Precision, Recall, F-score, Support on validation data
Precision [0.99956761 0.21258415]
Recall [0.99680956 0.6663961 ]
F-score [0.99818668 0.32234001]
Support [953161   1232]
*************************************

Performance on validation data - Confusion matrix
[[948435   4726]
 [   370    862]]
Precision, Recall, F-score, Support on validation data
Precision [0.99961004 0.15425913]
Recall [0.99504176 0.69967532]
F-score [0.99732067 0.25278592]
Support [953161   1232]
**************************************
Iteration number   73
Class weights  {0: 1, 1: 73}
Performance on validation data - Confusion matrix
[[948347   4814]
 [   369    863]]
Precision, Recall, F-score, Support on validation data
Precision [0.99961105 0.15201691]
Recall [0.99494944 0.70048701]
F-score [0.9972748  0.24981908]
Support [953161   1232]
**************************************
Iteration number   74
Class weights  {0: 1, 1: 74}
Performance on validation data - Confusion matrix
[[948263   4898]
 [   368    864]]
Precision, Recall, F-score, Support on validation data
Precision [0.99961207 0.14994793]
Recall [0.99486131 0.7012987 ]
F-score [0.99723103 0.24706892]
Support [953161   1232]
*************************************

Performance on validation data - Confusion matrix
[[946553   6608]
 [   325    907]]
Precision, Recall, F-score, Support on validation data
Precision [0.99965677 0.12069195]
Recall [0.99306728 0.7362013 ]
F-score [0.99635113 0.20738539]
Support [953161   1232]
**************************************
Iteration number   97
Class weights  {0: 1, 1: 97}
Performance on validation data - Confusion matrix
[[946469   6692]
 [   322    910]]
Precision, Recall, F-score, Support on validation data
Precision [0.9996599  0.11970534]
Recall [0.99297915 0.73863636]
F-score [0.99630833 0.20602219]
Support [953161   1232]
**************************************
Iteration number   98
Class weights  {0: 1, 1: 98}
Performance on validation data - Confusion matrix
[[946404   6757]
 [   320    912]]
Precision, Recall, F-score, Support on validation data
Precision [0.99966199 0.11892033]
Recall [0.99291096 0.74025974]
F-score [0.99627504 0.2049208 ]
Support [953161   1232]
*************************************

Precision, Recall, F-score, Support on validation data
Precision [0.999691   0.09985129]
Recall [0.99110958 0.76298701]
F-score [0.99538179 0.17659215]
Support [953161   1232]
**************************************
Iteration number   120
Class weights  {0: 1, 1: 120}
Performance on validation data - Confusion matrix
[[944612   8549]
 [   291    941]]
Precision, Recall, F-score, Support on validation data
Precision [0.99969203 0.09915701]
Recall [0.9910309 0.7637987]
F-score [0.99534262 0.17552695]
Support [953161   1232]
**************************************
Iteration number   121
Class weights  {0: 1, 1: 121}
Performance on validation data - Confusion matrix
[[944531   8630]
 [   291    941]]
Precision, Recall, F-score, Support on validation data
Precision [0.99969201 0.09831784]
Recall [0.99094592 0.7637987 ]
F-score [0.99529975 0.17421087]
Support [953161   1232]
**************************************
Iteration number   122
Class weights  {0: 1, 1: 122}
Performance on validation da

Performance on validation data - Confusion matrix
[[942886  10275]
 [   261    971]]
Precision, Recall, F-score, Support on validation data
Precision [0.99972327 0.08634181]
Recall [0.98922008 0.78814935]
F-score [0.99444394 0.15563392]
Support [953161   1232]
**************************************
Iteration number   144
Class weights  {0: 1, 1: 144}
Performance on validation data - Confusion matrix
[[942821  10340]
 [   261    971]]
Precision, Recall, F-score, Support on validation data
Precision [0.99972325 0.08584564]
Recall [0.98915189 0.78814935]
F-score [0.99440947 0.15482739]
Support [953161   1232]
**************************************
Iteration number   145
Class weights  {0: 1, 1: 145}
Performance on validation data - Confusion matrix
[[942741  10420]
 [   260    972]]
Precision, Recall, F-score, Support on validation data
Precision [0.99972428 0.08532303]
Recall [0.98906795 0.78896104]
F-score [0.99436757 0.1539924 ]
Support [953161   1232]
*********************************

Precision, Recall, F-score, Support on validation data
Precision [0.99974824 0.07650903]
Recall [0.98739982 0.80762987]
F-score [0.99353566 0.13977664]
Support [953161   1232]
**************************************
Iteration number   167
Class weights  {0: 1, 1: 167}
Performance on validation data - Confusion matrix
[[941050  12111]
 [   237    995]]
Precision, Recall, F-score, Support on validation data
Precision [0.99974822 0.07591943]
Recall [0.98729386 0.80762987]
F-score [0.99348201 0.13879202]
Support [953161   1232]
**************************************
Iteration number   168
Class weights  {0: 1, 1: 168}
Performance on validation data - Confusion matrix
[[940998  12163]
 [   237    995]]
Precision, Recall, F-score, Support on validation data
Precision [0.9997482 0.0756194]
Recall [0.9872393  0.80762987]
F-score [0.99345438 0.13829048]
Support [953161   1232]
**************************************
Iteration number   169
Class weights  {0: 1, 1: 169}
Performance on validation da

Performance on validation data - Confusion matrix
[[939203  13958]
 [   208   1024]]
Precision, Recall, F-score, Support on validation data
Precision [0.99977858 0.06834869]
Recall [0.98535609 0.83116883]
F-score [0.99251495 0.1263106 ]
Support [953161   1232]
**************************************
Iteration number   191
Class weights  {0: 1, 1: 191}
Performance on validation data - Confusion matrix
[[939124  14037]
 [   208   1024]]
Precision, Recall, F-score, Support on validation data
Precision [0.99977857 0.06799017]
Recall [0.98527321 0.83116883]
F-score [0.99247289 0.12569815]
Support [953161   1232]
**************************************
Iteration number   192
Class weights  {0: 1, 1: 192}
Performance on validation data - Confusion matrix
[[939047  14114]
 [   207   1025]]
Precision, Recall, F-score, Support on validation data
Precision [0.99977961 0.06770593]
Recall [0.98519243 0.83198052]
F-score [0.99243242 0.12522143]
Support [953161   1232]
*********************************

Precision, Recall, F-score, Support on validation data
Precision [0.99979094 0.06141807]
Recall [0.98339    0.84090909]
F-score [0.99152265 0.11447514]
Support [953161   1232]
**************************************
Iteration number   214
Class weights  {0: 1, 1: 214}
Performance on validation data - Confusion matrix
[[937248  15913]
 [   194   1038]]
Precision, Recall, F-score, Support on validation data
Precision [0.99979305 0.06123533]
Recall [0.98330502 0.84253247]
F-score [0.9914805  0.11417258]
Support [953161   1232]
**************************************
Iteration number   215
Class weights  {0: 1, 1: 215}
Performance on validation data - Confusion matrix
[[937166  15995]
 [   194   1038]]
Precision, Recall, F-score, Support on validation data
Precision [0.99979304 0.06094053]
Recall [0.98321899 0.84253247]
F-score [0.99143675 0.11366001]
Support [953161   1232]
**************************************
Iteration number   216
Class weights  {0: 1, 1: 216}
Performance on validation 

Performance on validation data - Confusion matrix
[[935471  17690]
 [   179   1053]]
Precision, Recall, F-score, Support on validation data
Precision [0.99980869 0.05618097]
Recall [0.9814407  0.85470779]
F-score [0.99053955 0.10543179]
Support [953161   1232]
**************************************
Iteration number   238
Class weights  {0: 1, 1: 238}
Performance on validation data - Confusion matrix
[[935399  17762]
 [   179   1053]]
Precision, Recall, F-score, Support on validation data
Precision [0.99980867 0.05596598]
Recall [0.98136516 0.85470779]
F-score [0.99050107 0.10505313]
Support [953161   1232]
**************************************
Iteration number   239
Class weights  {0: 1, 1: 239}
Performance on validation data - Confusion matrix
[[935336  17825]
 [   179   1053]]
Precision, Recall, F-score, Support on validation data
Precision [0.99980866 0.05577921]
Recall [0.98129907 0.85470779]
F-score [0.9904674  0.10472402]
Support [953161   1232]
*********************************

Precision, Recall, F-score, Support on validation data
Precision [0.99981578 0.05119042]
Recall [0.97938753 0.86038961]
F-score [0.98949623 0.09663157]
Support [953161   1232]
**************************************
Iteration number   261
Class weights  {0: 1, 1: 261}
Performance on validation data - Confusion matrix
[[933419  19742]
 [   171   1061]]
Precision, Recall, F-score, Support on validation data
Precision [0.99981684 0.05100226]
Recall [0.97928786 0.8612013 ]
F-score [0.98944588 0.09630134]
Support [953161   1232]
**************************************
Iteration number   262
Class weights  {0: 1, 1: 262}
Performance on validation data - Confusion matrix
[[933340  19821]
 [   171   1061]]
Precision, Recall, F-score, Support on validation data
Precision [0.99981682 0.05080931]
Recall [0.97920498 0.8612013 ]
F-score [0.98940356 0.09595731]
Support [953161   1232]
**************************************
Iteration number   263
Class weights  {0: 1, 1: 263}
Performance on validation 

Performance on validation data - Confusion matrix
[[931400  21761]
 [   165   1067]]
Precision, Recall, F-score, Support on validation data
Precision [0.99982288 0.04674084]
Recall [0.97716965 0.86607143]
F-score [0.98836648 0.08869493]
Support [953161   1232]
**************************************
Iteration number   285
Class weights  {0: 1, 1: 285}
Performance on validation data - Confusion matrix
[[931317  21844]
 [   165   1067]]
Precision, Recall, F-score, Support on validation data
Precision [0.99982286 0.04657152]
Recall [0.97708257 0.86607143]
F-score [0.98832193 0.08839001]
Support [953161   1232]
**************************************
Iteration number   286
Class weights  {0: 1, 1: 286}
Performance on validation data - Confusion matrix
[[931233  21928]
 [   164   1068]]
Precision, Recall, F-score, Support on validation data
Precision [0.99982392 0.04644286]
Recall [0.97699444 0.86688312]
F-score [0.98827736 0.08816246]
Support [953161   1232]
*********************************

Precision, Recall, F-score, Support on validation data
Precision [0.99982789 0.04325895]
Recall [0.97512592 0.87012987]
F-score [0.98732242 0.08242033]
Support [953161   1232]
**************************************
Iteration number   308
Class weights  {0: 1, 1: 308}
Performance on validation data - Confusion matrix
[[929364  23797]
 [   160   1072]]
Precision, Recall, F-score, Support on validation data
Precision [0.99982787 0.04310587]
Recall [0.9750336  0.87012987]
F-score [0.98727509 0.08214245]
Support [953161   1232]
**************************************
Iteration number   309
Class weights  {0: 1, 1: 309}
Performance on validation data - Confusion matrix
[[929279  23882]
 [   160   1072]]
Precision, Recall, F-score, Support on validation data
Precision [0.99982785 0.04295904]
Recall [0.97494442 0.87012987]
F-score [0.98722936 0.08187581]
Support [953161   1232]
**************************************
Iteration number   310
Class weights  {0: 1, 1: 310}
Performance on validation 

Performance on validation data - Confusion matrix
[[927471  25690]
 [   157   1075]]
Precision, Recall, F-score, Support on validation data
Precision [0.99983075 0.04016439]
Recall [0.97304758 0.87256494]
F-score [0.98625736 0.07679394]
Support [953161   1232]
**************************************
Iteration number   332
Class weights  {0: 1, 1: 332}
Performance on validation data - Confusion matrix
[[927392  25769]
 [   157   1075]]
Precision, Recall, F-score, Support on validation data
Precision [0.99983074 0.04004619]
Recall [0.97296469 0.87256494]
F-score [0.98621478 0.07657786]
Support [953161   1232]
**************************************
Iteration number   333
Class weights  {0: 1, 1: 333}
Performance on validation data - Confusion matrix
[[927316  25845]
 [   157   1075]]
Precision, Recall, F-score, Support on validation data
Precision [0.99983072 0.03993314]
Recall [0.97288496 0.87256494]
F-score [0.98617381 0.07637113]
Support [953161   1232]
*********************************

Precision, Recall, F-score, Support on validation data
Precision [0.99983151 0.03772526]
Recall [0.97120528 0.87337662]
F-score [0.98531052 0.07232641]
Support [953161   1232]
**************************************
Iteration number   355
Class weights  {0: 1, 1: 355}
Performance on validation data - Confusion matrix
[[925638  27523]
 [   156   1076]]
Precision, Recall, F-score, Support on validation data
Precision [0.9998315  0.03762369]
Recall [0.9711245  0.87337662]
F-score [0.98526894 0.07213972]
Support [953161   1232]
**************************************
Iteration number   356
Class weights  {0: 1, 1: 356}
Performance on validation data - Confusion matrix
[[925562  27599]
 [   155   1077]]
Precision, Recall, F-score, Support on validation data
Precision [0.99983256 0.03755754]
Recall [0.97104477 0.87418831]
F-score [0.98522842 0.07202086]
Support [953161   1232]
**************************************
Iteration number   357
Class weights  {0: 1, 1: 357}
Performance on validation 

Performance on validation data - Confusion matrix
[[923941  29220]
 [   152   1080]]
Precision, Recall, F-score, Support on validation data
Precision [0.99983551 0.03564356]
Recall [0.96934411 0.87662338]
F-score [0.98435374 0.06850184]
Support [953161   1232]
**************************************
Iteration number   379
Class weights  {0: 1, 1: 379}
Performance on validation data - Confusion matrix
[[923853  29308]
 [   152   1080]]
Precision, Recall, F-score, Support on validation data
Precision [0.9998355  0.03554034]
Recall [0.96925178 0.87662338]
F-score [0.98430613 0.0683112 ]
Support [953161   1232]
**************************************
Iteration number   380
Class weights  {0: 1, 1: 380}
Performance on validation data - Confusion matrix
[[923776  29385]
 [   152   1080]]
Precision, Recall, F-score, Support on validation data
Precision [0.99983549 0.03545052]
Recall [0.969171   0.87662338]
F-score [0.98426446 0.06814525]
Support [953161   1232]
*********************************

Precision, Recall, F-score, Support on validation data
Precision [0.99983846 0.03380361]
Recall [0.96752385 0.87905844]
F-score [0.98341576 0.0651037 ]
Support [953161   1232]
**************************************
Iteration number   402
Class weights  {0: 1, 1: 402}
Performance on validation data - Confusion matrix
[[922128  31033]
 [   149   1083]]
Precision, Recall, F-score, Support on validation data
Precision [0.99983844 0.03372151]
Recall [0.96744202 0.87905844]
F-score [0.98337348 0.06495142]
Support [953161   1232]
**************************************
Iteration number   403
Class weights  {0: 1, 1: 403}
Performance on validation data - Confusion matrix
[[922049  31112]
 [   149   1083]]
Precision, Recall, F-score, Support on validation data
Precision [0.99983843 0.03363876]
Recall [0.96735913 0.87905844]
F-score [0.98333066 0.06479792]
Support [953161   1232]
**************************************
Iteration number   404
Class weights  {0: 1, 1: 404}
Performance on validation 

Performance on validation data - Confusion matrix
[[920436  32725]
 [   149   1083]]
Precision, Recall, F-score, Support on validation data
Precision [0.99983815 0.03203384]
Recall [0.96566687 0.87905844]
F-score [0.98245547 0.06181507]
Support [953161   1232]
**************************************
Iteration number   426
Class weights  {0: 1, 1: 426}
Performance on validation data - Confusion matrix
[[920361  32800]
 [   149   1083]]
Precision, Recall, F-score, Support on validation data
Precision [0.99983813 0.03196293]
Recall [0.96558818 0.87905844]
F-score [0.98241474 0.06168304]
Support [953161   1232]
**************************************
Iteration number   427
Class weights  {0: 1, 1: 427}
Performance on validation data - Confusion matrix
[[920285  32876]
 [   149   1083]]
Precision, Recall, F-score, Support on validation data
Precision [0.99983812 0.0318914 ]
Recall [0.96550845 0.87905844]
F-score [0.98237346 0.06154983]
Support [953161   1232]
*********************************

Precision, Recall, F-score, Support on validation data
Precision [0.9998444  0.03076619]
Recall [0.96400713 0.88392857]
F-score [0.98159878 0.05946271]
Support [953161   1232]
**************************************
Iteration number   449
Class weights  {0: 1, 1: 449}
Performance on validation data - Confusion matrix
[[918788  34373]
 [   143   1089]]
Precision, Recall, F-score, Support on validation data
Precision [0.99984438 0.03070893]
Recall [0.96393789 0.88392857]
F-score [0.98156287 0.05935575]
Support [953161   1232]
**************************************
Iteration number   450
Class weights  {0: 1, 1: 450}
Performance on validation data - Confusion matrix
[[918713  34448]
 [   143   1089]]
Precision, Recall, F-score, Support on validation data
Precision [0.99984437 0.03064412]
Recall [0.9638592  0.88392857]
F-score [0.98152207 0.05923468]
Support [953161   1232]
**************************************
Iteration number   451
Class weights  {0: 1, 1: 451}
Performance on validation 

Performance on validation data - Confusion matrix
[[917260  35901]
 [   141   1091]]
Precision, Recall, F-score, Support on validation data
Precision [0.9998463  0.02949286]
Recall [0.9623348  0.88555195]
F-score [0.98073199 0.05708455]
Support [953161   1232]
**************************************
Iteration number   473
Class weights  {0: 1, 1: 473}
Performance on validation data - Confusion matrix
[[917193  35968]
 [   141   1091]]
Precision, Recall, F-score, Support on validation data
Precision [0.99984629 0.02943954]
Recall [0.96226451 0.88555195]
F-score [0.98069548 0.05698467]
Support [953161   1232]
**************************************
Iteration number   474
Class weights  {0: 1, 1: 474}
Performance on validation data - Confusion matrix
[[917125  36036]
 [   141   1091]]
Precision, Recall, F-score, Support on validation data
Precision [0.99984628 0.02938562]
Recall [0.96219317 0.88555195]
F-score [0.98065843 0.05688365]
Support [953161   1232]
*********************************

Precision, Recall, F-score, Support on validation data
Precision [0.99984714 0.02833493]
Recall [0.96071283 0.88636364]
F-score [0.97988941 0.05491438]
Support [953161   1232]
**************************************
Iteration number   496
Class weights  {0: 1, 1: 496}
Performance on validation data - Confusion matrix
[[915655  37506]
 [   140   1092]]
Precision, Recall, F-score, Support on validation data
Precision [0.99984713 0.02829162]
Recall [0.96065093 0.88636364]
F-score [0.9798572  0.05483304]
Support [953161   1232]
**************************************
Iteration number   497
Class weights  {0: 1, 1: 497}
Performance on validation data - Confusion matrix
[[915596  37565]
 [   139   1093]]
Precision, Recall, F-score, Support on validation data
Precision [0.99984821 0.02827358]
Recall [0.96058903 0.88717532]
F-score [0.97982552 0.0548007 ]
Support [953161   1232]
**************************************
Iteration number   498
Class weights  {0: 1, 1: 498}
Performance on validation 